//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_attandanceGroup
    {
        public int AcadYearID { get; set; }
        public int IdWs { get; set; }
        public int EmployeeID { get; set; }
        public int GroupID { get; set; }
        public int SubjectID { get; set; }
    }
}
