//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ab_fio
    {
        public int id_student { get; set; }
        public string ab_fio1 { get; set; }
        public Nullable<bool> isStudent { get; set; }
        public bool del { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public string idid { get; set; }
    }
}
