//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ab_InfoOnEdIns
    {
        public int id_InfoOnEdIns { get; set; }
        public int IDStudent { get; set; }
        public Nullable<int> id_learn_lang { get; set; }
        public Nullable<int> CallEdIns { get; set; }
        public Nullable<int> TypeScholl { get; set; }
        public Nullable<bool> SertRespTest { get; set; }
        public string NumberSertRT { get; set; }
        public Nullable<int> BallOnRepsTest { get; set; }
        public string YearTerminations { get; set; }
        public Nullable<bool> OnExcellent { get; set; }
        public Nullable<bool> WithMedal { get; set; }
        public Nullable<bool> PrizeOfOlympiad { get; set; }
        public Nullable<bool> Atestat { get; set; }
        public string SeriesAD { get; set; }
        public string NumberAD { get; set; }
        public Nullable<bool> ADOriginal { get; set; }
        public Nullable<int> LanguageEduc { get; set; }
        public Nullable<int> PlaseSertORT { get; set; }
        public Nullable<int> OtherBallORT { get; set; }
        public int TourORT { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public string AVN_User_Update { get; set; }
        public Nullable<int> ORT_biology { get; set; }
        public Nullable<int> ORT_history { get; set; }
        public Nullable<int> ORT_chemistry { get; set; }
        public Nullable<int> ORT_physics { get; set; }
        public Nullable<int> ORT_english { get; set; }
        public Nullable<int> ORT_math { get; set; }
    
        public virtual CallEducationInst CallEducationInst { get; set; }
    }
}
