//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class abit_1
    {
        public int id_faculty { get; set; }
        public string p23_1 { get; set; }
        public Nullable<int> all_st { get; set; }
        public Nullable<int> sert_st { get; set; }
        public Nullable<int> st_budj { get; set; }
        public Nullable<int> st_kontr { get; set; }
        public Nullable<int> st_recom_b { get; set; }
        public Nullable<int> st_recom_k { get; set; }
        public Nullable<int> st_confirm_b { get; set; }
        public Nullable<int> st_confirm_k { get; set; }
        public Nullable<int> kol_b { get; set; }
        public Nullable<int> kol_k { get; set; }
        public Nullable<int> dz { get; set; }
        public Nullable<int> bz_vh { get; set; }
        public Nullable<int> bz_nevh { get; set; }
        public string p23_2 { get; set; }
    }
}
