//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abit_svod_kateg2
    {
        public int id_student { get; set; }
        public bool del { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<bool> SertRespTest { get; set; }
        public string NumberSertRT { get; set; }
        public Nullable<int> PlaseSertORT { get; set; }
        public string NamePlase { get; set; }
        public int TourORT { get; set; }
        public Nullable<int> BallOnRepsTest { get; set; }
        public int biolog { get; set; }
        public int history { get; set; }
        public int chemistry { get; set; }
        public int phisics { get; set; }
        public int english { get; set; }
        public int math { get; set; }
        public Nullable<int> Speciality { get; set; }
        public Nullable<int> Faculties { get; set; }
        public byte tour { get; set; }
        public bool recom { get; set; }
        public bool podt { get; set; }
        public bool zachisl { get; set; }
        public bool zabral { get; set; }
        public short id_bk { get; set; }
        public string name { get; set; }
        public Nullable<int> id_category { get; set; }
        public string n_category { get; set; }
        public Nullable<bool> Orphan { get; set; }
        public Nullable<bool> Invalid12Group { get; set; }
    }
}
