//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbitRecom_zachisl_pivot
    {
        public Nullable<int> id_a_year { get; set; }
        public byte tour { get; set; }
        public int id_bk { get; set; }
        public bool recom { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public Nullable<int> id_direction { get; set; }
        public int id_speciality { get; set; }
        public int Bishkek { get; set; }
        public int Town { get; set; }
        public int Village { get; set; }
        public int Highlands { get; set; }
    }
}
