//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class abit_temp_direction
    {
        public int id_a_year { get; set; }
        public int id_faculty { get; set; }
        public string p23_1 { get; set; }
        public Nullable<int> id_direction { get; set; }
        public string p24_1 { get; set; }
        public string p24_2 { get; set; }
    }
}
