//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abit_svod_kateg_PLAN
    {
        public Nullable<int> id_a_year { get; set; }
        public int id_faculty { get; set; }
        public Nullable<int> id_direction { get; set; }
        public int id_speciality { get; set; }
        public int kol_b { get; set; }
        public Nullable<byte> tur { get; set; }
        public Nullable<int> id_bk { get; set; }
    }
}
