//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_good_onlinepayment
    {
        public long id_onlinePaymentStream { get; set; }
        public int Expr1 { get; set; }
        public string account { get; set; }
        public string @operator { get; set; }
        public string txn_id { get; set; }
        public System.DateTime txn_date { get; set; }
        public float sum { get; set; }
        public string payerName { get; set; }
        public string place { get; set; }
        public bool isCanceled { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_abiturient { get; set; }
        public string additional { get; set; }
        public Nullable<long> id_onlinePaymentPreparedAccount { get; set; }
        public Nullable<bool> isOnlinePaymentStreamCanceled { get; set; }
    }
}
