//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_KyrgazstanBank_Unhandled_List
    {
        public int id { get; set; }
        public string s_fio { get; set; }
        public Nullable<int> id_rate { get; set; }
        public Nullable<float> sum { get; set; }
        public int id_s_g { get; set; }
        public string account { get; set; }
    }
}
