//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class akad_grafik
    {
        public int id_akad_grafik { get; set; }
        public Nullable<int> id_year { get; set; }
        public Nullable<System.DateTime> KT_osen_beg { get; set; }
        public Nullable<System.DateTime> KT_osen_end { get; set; }
        public Nullable<System.DateTime> RK_osen_beg { get; set; }
        public Nullable<System.DateTime> RK_osen_end { get; set; }
        public Nullable<System.DateTime> KT_vesen_beg { get; set; }
        public Nullable<System.DateTime> KT_vesen_end { get; set; }
        public Nullable<System.DateTime> RK_vesen_beg { get; set; }
        public Nullable<System.DateTime> RK_vesen_end { get; set; }
        public Nullable<System.DateTime> letnii_beg { get; set; }
        public Nullable<System.DateTime> letnii_end { get; set; }
    }
}
