//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ank_fak_gr_st
    {
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public int id_group { get; set; }
        public int id_semester { get; set; }
        public int id_teacher { get; set; }
        public int id_discipline { get; set; }
        public int id_student { get; set; }
        public int id_mark_mag { get; set; }
        public string p23_1 { get; set; }
        public Nullable<int> StudentId { get; set; }
    }
}
