//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anketirovanie_net
    {
        public int QuestionnairesId { get; set; }
        public int YearId { get; set; }
        public int id_w_s { get; set; }
        public int SemesterId { get; set; }
        public int TeacherId { get; set; }
        public int DisciplineId { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> NET { get; set; }
    }
}
