//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anketirovanie_RS_kaf
    {
        public int id_a_year { get; set; }
        public int id_w_s { get; set; }
        public int QuestionnairesId { get; set; }
        public string Description { get; set; }
        public string DescriptionKg { get; set; }
        public string Answer { get; set; }
        public Nullable<int> id_kafedra { get; set; }
    }
}
