//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class anket_kaf1
    {
        public int YearId { get; set; }
        public int id_w_s { get; set; }
        public int id_kafedra { get; set; }
        public int TeacherId { get; set; }
        public Nullable<double> ball1 { get; set; }
        public Nullable<double> ball2 { get; set; }
        public Nullable<double> ball3 { get; set; }
        public Nullable<double> ball4 { get; set; }
        public Nullable<double> ball5 { get; set; }
        public Nullable<double> ball6 { get; set; }
        public Nullable<double> ball7 { get; set; }
        public Nullable<double> ball8 { get; set; }
        public Nullable<double> ball9 { get; set; }
        public Nullable<double> ball10 { get; set; }
        public Nullable<double> ball11 { get; set; }
        public Nullable<double> ball12 { get; set; }
        public Nullable<double> ball13 { get; set; }
    }
}
