//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anketirovanie_Questions
    {
        public int Id { get; set; }
        public int QuestionnaireId { get; set; }
        public string QuestionRu { get; set; }
        public string QuestionKg { get; set; }
        public string AnswerType { get; set; }
    }
}
