//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anketirovarie_Kol_Full
    {
        public int QuestionnairesId { get; set; }
        public int YearId { get; set; }
        public int id_w_s { get; set; }
        public int SemesterId { get; set; }
        public int TeacherId { get; set; }
        public int DisciplineId { get; set; }
        public Nullable<int> kol1 { get; set; }
        public Nullable<int> kol2 { get; set; }
        public Nullable<int> kol3 { get; set; }
        public Nullable<int> kol4 { get; set; }
        public Nullable<int> kol5 { get; set; }
    }
}
