//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antekirovanie_RS_kafedra
    {
        public Nullable<int> id_a_year { get; set; }
        public string p32 { get; set; }
        public int id_w_s { get; set; }
        public string p42 { get; set; }
        public int id_kafedra { get; set; }
        public string f1 { get; set; }
        public int id_teacher { get; set; }
        public string t_fio { get; set; }
        public Nullable<int> stud { get; set; }
        public Nullable<int> sdal { get; set; }
        public Nullable<int> anket { get; set; }
        public Nullable<decimal> v1 { get; set; }
        public Nullable<decimal> v2 { get; set; }
        public Nullable<decimal> v3 { get; set; }
        public Nullable<decimal> v4 { get; set; }
        public Nullable<decimal> v5 { get; set; }
        public Nullable<decimal> v6 { get; set; }
        public Nullable<decimal> v7 { get; set; }
        public Nullable<decimal> v8 { get; set; }
        public Nullable<decimal> v9 { get; set; }
        public Nullable<decimal> v10 { get; set; }
        public Nullable<decimal> v11 { get; set; }
        public Nullable<decimal> v12 { get; set; }
        public Nullable<decimal> v13 { get; set; }
        public Nullable<decimal> s_sum { get; set; }
    }
}
