//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class aud_discip_rasp
    {
        public int id_aud_discip_rasp { get; set; }
        public Nullable<int> id_auditorium { get; set; }
        public Nullable<int> id_discipline { get; set; }
    }
}
