//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoriums
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auditoriums()
        {
            this.SCHDayOffAuditories = new HashSet<SCHDayOffAuditories>();
        }
    
        public int id_auditorium { get; set; }
        public Nullable<int> id_korpus { get; set; }
        public string number { get; set; }
        public int contain { get; set; }
        public Nullable<int> specific { get; set; }
        public string note { get; set; }
        public Nullable<double> square { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public Nullable<int> id_otdel_1 { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public Nullable<int> body { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCHDayOffAuditories> SCHDayOffAuditories { get; set; }
        public virtual Specifics Specifics { get; set; }
    }
}
