//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVN_rep_user
    {
        public int id_AVN_rep_user { get; set; }
        public Nullable<int> id_avn_user { get; set; }
        public Nullable<int> id_avn_report_role { get; set; }
    
        public virtual AVN_report_role AVN_report_role { get; set; }
    }
}
