//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVN_Test_vopros
    {
        public int id_test_vopros { get; set; }
        public string names { get; set; }
        public Nullable<int> id_test_type { get; set; }
        public Nullable<int> id_test_category { get; set; }
    }
}
