//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVN_svyazi
    {
        public int id_AVN_svyazi { get; set; }
        public string vopros { get; set; }
        public string osn_table_name { get; set; }
        public string osn_ident_name { get; set; }
        public string dop_table_name { get; set; }
        public string dop_ident_name { get; set; }
        public bool isHandled { get; set; }
        public int dop_table_from_id { get; set; }
        public int rows { get; set; }
        public int affected { get; set; }
        public int order { get; set; }
    }
}
