//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVN_TEST_TestResult
    {
        public int id_AVN_TEST_TestResult { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> id_test { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_fac { get; set; }
        public Nullable<int> ig_group { get; set; }
        public Nullable<int> id_semestr { get; set; }
        public Nullable<int> id_disciplina { get; set; }
        public Nullable<int> id_examination { get; set; }
        public Nullable<int> id_regulation { get; set; }
        public string VidTesta { get; set; }
        public byte[] questions { get; set; }
        public byte[] answers { get; set; }
        public Nullable<int> attempt { get; set; }
        public string zdal { get; set; }
        public Nullable<int> pOtv { get; set; }
        public Nullable<int> ball { get; set; }
        public byte[] image { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> GenerateDate { get; set; }
        public string IpAddress { get; set; }
        public string pole { get; set; }
        public Nullable<int> id_pole { get; set; }
        public Nullable<System.DateTime> AVNUPDATE { get; set; }
        public Nullable<int> RightAnsvers { get; set; }
        public Nullable<int> id_f_e { get; set; }
        public bool isHandled { get; set; }
    }
}
