//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVN_Log
    {
        public int id_avn_log { get; set; }
        public string table { get; set; }
        public int row_id { get; set; }
        public string descr { get; set; }
        public string comp { get; set; }
        public string AVN_User { get; set; }
        public Nullable<System.DateTime> AVN_Update { get; set; }
        public Nullable<byte> logStatus { get; set; }
    }
}
