//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVNLOG_3
    {
        public int id_user { get; set; }
        public int id_discipline { get; set; }
        public string p20 { get; set; }
        public string s_fio { get; set; }
        public string p34 { get; set; }
        public int id_semester { get; set; }
        public int id_student { get; set; }
        public int id_group { get; set; }
    }
}
