//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_payment_5
    {
        public System.DateTime p103 { get; set; }
        public string Code { get; set; }
        public double sum { get; set; }
        public int id_v_opl { get; set; }
        public string primech { get; set; }
    }
}
