//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_akt_sverka3
    {
        public System.DateTime txn_date { get; set; }
        public string CODE { get; set; }
        public float suma { get; set; }
        public string s_fio { get; set; }
        public int id_uslug { get; set; }
        public int id_student { get; set; }
    }
}
