//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class bf_0
    {
        public Nullable<int> id_student { get; set; }
        public Nullable<double> P102 { get; set; }
        public Nullable<int> id_rate { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public System.DateTime p103 { get; set; }
        public int p104 { get; set; }
        public System.DateTime dateopl { get; set; }
    }
}
