//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class bf_1_2
    {
        public int id_group { get; set; }
        public int id_rate { get; set; }
        public int id_student { get; set; }
        public int id_a_year { get; set; }
        public Nullable<double> s_p106 { get; set; }
        public Nullable<int> id_country { get; set; }
        public string s_fio { get; set; }
        public Nullable<int> opl { get; set; }
        public Nullable<double> p106 { get; set; }
        public int id_StudentDiscount { get; set; }
    }
}
