//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bronya
    {
        public int id_shcedule { get; set; }
        public Nullable<int> kod_prepod { get; set; }
        public Nullable<int> id_auditorium { get; set; }
        public string id_potok { get; set; }
        public Nullable<int> id_day { get; set; }
        public Nullable<int> id_time { get; set; }
        public Nullable<int> kod_predmet { get; set; }
        public Nullable<int> id_rab { get; set; }
        public Nullable<int> bron_chas { get; set; }
        public Nullable<int> id_year { get; set; }
        public Nullable<int> id_semestr { get; set; }
    
        public virtual discipline discipline { get; set; }
        public virtual teacher teacher { get; set; }
        public virtual Time_ Time_ { get; set; }
    }
}
