//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class C11
    {
        public int id_faculty { get; set; }
        public int id_country { get; set; }
        public string s_p14_7 { get; set; }
        public int id_Citizenship { get; set; }
        public string Citizenship { get; set; }
        public int id_Nationality { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> kol_st { get; set; }
        public bool Male { get; set; }
    }
}
