//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class C___Directions
    {
        public int IDRecord { get; set; }
        public short IDFaculties { get; set; }
        public string IDDirections { get; set; }
        public string NameDirections { get; set; }
        public string SmallNameDirect { get; set; }
        public short FormSt { get; set; }
        public string Apprenticeship { get; set; }
        public int LicenceNum { get; set; }
        public short QualificationName { get; set; }
        public short StandardOfEducation { get; set; }
        public int CountStudens { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
    }
}
