//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__Z_USPEV_UC
    {
        public Nullable<int> id_a_year { get; set; }
        public int id_semester { get; set; }
        public int id_student { get; set; }
        public int id_group { get; set; }
        public int id_discipline { get; set; }
        public int id_examination { get; set; }
        public int Krdt { get; set; }
        public Nullable<double> ball { get; set; }
        public Nullable<System.DateTime> p36 { get; set; }
        public Nullable<int> id_estimation { get; set; }
        public Nullable<int> id_ebe_var { get; set; }
    }
}
