//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallEducationInst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CallEducationInst()
        {
            this.Ab_InfoOnEdIns = new HashSet<Ab_InfoOnEdIns>();
            this.InfoOnEdIns = new HashSet<InfoOnEdIns>();
        }
    
        public int IDCall { get; set; }
        public int TypeEdIns { get; set; }
        public int RegionEducat { get; set; }
        public int DistrictEducat { get; set; }
        public Nullable<int> CityEducat { get; set; }
        public Nullable<int> VillageEducat { get; set; }
        public string CallEducat { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public Nullable<int> RepublicEducat { get; set; }
        public Nullable<bool> visible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ab_InfoOnEdIns> Ab_InfoOnEdIns { get; set; }
        public virtual TypeScholl TypeScholl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoOnEdIns> InfoOnEdIns { get; set; }
    }
}
