//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debts
    {
        public int id_debts { get; set; }
        public Nullable<int> id_semester { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_discipline { get; set; }
    }
}
