//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Def_Uslug
    {
        public int id_def_uslug { get; set; }
        public Nullable<int> f1 { get; set; }
        public Nullable<int> f2 { get; set; }
        public Nullable<int> f3_1 { get; set; }
        public Nullable<int> f3_2 { get; set; }
        public Nullable<int> id_kassa { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public Nullable<int> opl_leto { get; set; }
    }
}
