//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Del_movement_t
    {
        public int id_protocols { get; set; }
        public int id_group { get; set; }
        public int id_student { get; set; }
        public int id_rate { get; set; }
        public int id_semester { get; set; }
        public Nullable<int> id_bk { get; set; }
        public string oper { get; set; }
        public Nullable<System.DateTime> u_date { get; set; }
        public int id_come { get; set; }
        public string come_reg { get; set; }
        public Nullable<System.DateTime> come_date { get; set; }
        public int id_leave { get; set; }
        public string leave_reg { get; set; }
        public Nullable<System.DateTime> leave_date { get; set; }
        public Nullable<bool> Check_ch { get; set; }
        public System.DateTime del_date { get; set; }
        public string del_oper { get; set; }
        public string descr { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
    }
}
