//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Del_payment
    {
        public int id_payment_del { get; set; }
        public string host_del { get; set; }
        public string oper_del { get; set; }
        public Nullable<int> id_payment { get; set; }
        public Nullable<int> pe { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_abiturient { get; set; }
        public string dopol { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public Nullable<int> id_oplata { get; set; }
        public string osnovanie { get; set; }
        public string primech { get; set; }
        public Nullable<int> id_speciality { get; set; }
        public Nullable<int> id_rate { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_uslug { get; set; }
        public Nullable<double> p102 { get; set; }
        public Nullable<System.DateTime> p103 { get; set; }
        public Nullable<int> p104 { get; set; }
        public string p104_1 { get; set; }
        public Nullable<int> id_v_opl { get; set; }
        public Nullable<System.DateTime> data_prikaz { get; set; }
        public string dop_info { get; set; }
        public string num_prikaz { get; set; }
        public string oper { get; set; }
        public Nullable<System.DateTime> u_date { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public Nullable<int> id_kassa { get; set; }
        public Nullable<int> new_speciality { get; set; }
        public Nullable<int> old_rate { get; set; }
        public Nullable<double> p102Next { get; set; }
        public Nullable<int> id_a_yearNext { get; set; }
        public Nullable<double> p102NewSpec { get; set; }
        public Nullable<int> id_newSpecP102 { get; set; }
        public Nullable<int> id_newYear { get; set; }
        public Nullable<int> id_newRate { get; set; }
        public Nullable<int> id_newGroup { get; set; }
        public string tmp { get; set; }
        public Nullable<int> id_slushatel { get; set; }
        public Nullable<int> id_group_slushatel { get; set; }
        public Nullable<double> temp_minus { get; set; }
        public Nullable<int> mov_move { get; set; }
        public string host { get; set; }
    }
}
