//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIPL_PRIX
    {
        public int ID_D { get; set; }
        public string S_FIO { get; set; }
        public System.DateTime d_oprix { get; set; }
        public string NOMER { get; set; }
        public float SENA { get; set; }
        public int ID_STUD { get; set; }
    }
}
