//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ebe_detal
    {
        public int id_ebe_detal { get; set; }
        public Nullable<int> id_ebe { get; set; }
        public Nullable<double> beg_bal { get; set; }
        public Nullable<double> end_bal { get; set; }
        public Nullable<double> ekv_num { get; set; }
        public string ekv_bukv { get; set; }
    }
}
