//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ed_sh_gr
    {
        public string p32 { get; set; }
        public string p43 { get; set; }
        public string p34 { get; set; }
        public string p26 { get; set; }
        public string p30 { get; set; }
        public string p45 { get; set; }
        public double p51 { get; set; }
        public double p52 { get; set; }
        public double p53 { get; set; }
        public double p54 { get; set; }
        public string p20 { get; set; }
        public string f1 { get; set; }
    }
}
