//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Educ
    {
        public int id_educ { get; set; }
        public Nullable<int> id_edu { get; set; }
        public Nullable<System.DateTime> Date_enter { get; set; }
        public Nullable<System.DateTime> Date_End { get; set; }
        public string Faculty { get; set; }
        public Nullable<int> id_educ_t { get; set; }
        public Nullable<int> id_quit_course { get; set; }
        public Nullable<int> id_special { get; set; }
        public int id_teacher { get; set; }
        public string Diploma_No { get; set; }
        public string vuz { get; set; }
        public Nullable<int> id_diploma_kval { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
    
        public virtual Diploma_kval Diploma_kval { get; set; }
        public virtual Edu Edu { get; set; }
        public virtual Educ_t Educ_t { get; set; }
        public virtual Quit_Course Quit_Course { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
