//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Educ_sh_sel
    {
        public int id_educ_sh_sel { get; set; }
        public Nullable<int> id_speciality { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_semester { get; set; }
        public Nullable<int> id_disciplineName { get; set; }
        public Nullable<bool> isDeletable { get; set; }
        public string avn_user { get; set; }
        public Nullable<System.DateTime> avn_update { get; set; }
    }
}
