//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class f16_1_1_1
    {
        public int id_faculty { get; set; }
        public int id_a_year { get; set; }
        public int id_rate { get; set; }
        public int id_teacher { get; set; }
        public int id_discipline { get; set; }
        public int kol { get; set; }
        public int id_semester { get; set; }
    }
}
