//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class f1_1
    {
        public int id_group { get; set; }
        public int id_a_year { get; set; }
        public int id_semester { get; set; }
        public int id_discipline { get; set; }
        public int id_examination { get; set; }
        public int id_educ_sh { get; set; }
        public Nullable<int> descGroupNum { get; set; }
        public Nullable<double> koefZD { get; set; }
        public Nullable<int> Krdt { get; set; }
        public Nullable<int> id_component { get; set; }
        public Nullable<int> id_kind { get; set; }
    }
}
