//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class f1_4sel
    {
        public Nullable<int> id_estimation { get; set; }
        public string t_fio { get; set; }
        public Nullable<int> id_mark_mag { get; set; }
        public int id_student { get; set; }
        public Nullable<int> descGroupNum { get; set; }
        public int id_educ_sh { get; set; }
        public int id_examination { get; set; }
        public int id_discipline { get; set; }
        public int id_semester { get; set; }
        public int id_a_year { get; set; }
        public int id_group { get; set; }
        public int rate { get; set; }
    }
}
