//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class f28_gruppa
    {
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_login { get; set; }
        public Nullable<int> id_group { get; set; }
        public string p20 { get; set; }
        public int id_speciality { get; set; }
        public int id_f_educ { get; set; }
        public Nullable<int> id_semester { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> id_examination { get; set; }
    }
}
