//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class f3_1
    {
        public int id_a_year { get; set; }
        public int id_faculty { get; set; }
        public int id_special { get; set; }
        public string p32 { get; set; }
        public string p25_1 { get; set; }
        public string p25_2 { get; set; }
    }
}
