//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class f_educ
    {
        public int id_f_educ { get; set; }
        public string p108_1 { get; set; }
        public string p108 { get; set; }
        public Nullable<int> o_z { get; set; }
        public Nullable<int> max_rate_id { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public Nullable<int> id_f_educ_vid { get; set; }
        public string p108k { get; set; }
        public Nullable<int> o_z_d { get; set; }
        public Nullable<int> sort { get; set; }
        public int sort_schedule { get; set; }
        public string z_o_d { get; set; }
    }
}
