//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_FIO
    {
        public int id_teacher { get; set; }
        public string F_FIO1 { get; set; }
        public Nullable<int> id_family_s { get; set; }
        public int id_family { get; set; }
        public Nullable<int> Old { get; set; }
    }
}
