//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class faculty
    {
        public int id_faculty { get; set; }
        public string p23_1 { get; set; }
        public string p23_2 { get; set; }
        public string NameFaculty { get; set; }
        public int id_vuz { get; set; }
        public Nullable<bool> priem_abit { get; set; }
        public string p23_2_k { get; set; }
        public Nullable<int> sort { get; set; }
        public string id_ua { get; set; }
        public string C__code { get; set; }
        public string p23_3 { get; set; }
        public string p23_4 { get; set; }
        public string n_director { get; set; }
        public string stukture { get; set; }
        public Nullable<int> f_group { get; set; }
        public string p23_2_1 { get; set; }
        public Nullable<byte> RS { get; set; }
        public string p_komissi { get; set; }
        public string doljnost { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public Nullable<byte> Visible_TV_abit { get; set; }
        public Nullable<int> RS_opl { get; set; }
        public Nullable<int> o_z { get; set; }
    
        public virtual vuz vuz { get; set; }
    }
}
