//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class family_
    {
        public int id_family { get; set; }
        public Nullable<int> id_family_status { get; set; }
        public Nullable<int> id_family_s { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public string Address { get; set; }
        public Nullable<int> id_family_job { get; set; }
        public string Org_Address { get; set; }
        public int id_teacher { get; set; }
        public string p26 { get; set; }
        public string p27 { get; set; }
        public string p28 { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
    
        public virtual family family { get; set; }
        public virtual Family_s Family_s { get; set; }
        public virtual Family_spec Family_spec { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
