//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class for_arch_marg_mag
    {
        public int id_mark_mag { get; set; }
        public int id_leave { get; set; }
        public string p20 { get; set; }
        public int id_group { get; set; }
        public int id_student { get; set; }
        public int id_semester { get; set; }
        public int id_discipline { get; set; }
        public int id_teacher { get; set; }
        public int id_estimation { get; set; }
    }
}
