//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class formAction
    {
        public int id_form_action { get; set; }
        public string ip { get; set; }
        public string compName { get; set; }
        public string inputLogin { get; set; }
        public string progAVN { get; set; }
        public Nullable<byte> id_action { get; set; }
        public Nullable<System.DateTime> a_date { get; set; }
        public Nullable<short> whoType { get; set; }
    }
}
