//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPA
    {
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_semester { get; set; }
        public int kredits { get; set; }
        public Nullable<double> ekv_num { get; set; }
        public int end_ses { get; set; }
        public Nullable<double> kr_ekvnum { get; set; }
    }
}
