//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class gr_year_spec_oz_fac
    {
        public int id_group { get; set; }
        public string p20 { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public int id_faculty { get; set; }
        public int id_speciality { get; set; }
        public int id_f_educ { get; set; }
        public Nullable<int> o_z { get; set; }
        public string id_sub_group { get; set; }
    }
}
