//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_kol_yaer
    {
        public int id_group { get; set; }
        public string p20 { get; set; }
        public Nullable<int> kol_b { get; set; }
        public Nullable<int> kol_k { get; set; }
        public Nullable<int> id_rate { get; set; }
        public Nullable<int> x { get; set; }
        public int id_a_year { get; set; }
    }
}
