//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class groups
    {
        public string p20 { get; set; }
        public int id_speciality { get; set; }
        public int id_group_y { get; set; }
        public int id_n_gr { get; set; }
        public string id_sub_group { get; set; }
        public int id_group { get; set; }
    }
}
