//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ind_ved_ar
    {
        public int id_a_year { get; set; }
        public int id_group { get; set; }
        public int id_student { get; set; }
        public int id_semester { get; set; }
        public int id_discipline { get; set; }
        public int id_examination { get; set; }
        public Nullable<int> id_estimation { get; set; }
        public int id_kafedra { get; set; }
        public Nullable<double> ball { get; set; }
        public Nullable<System.DateTime> p36 { get; set; }
        public Nullable<int> id_f_est { get; set; }
        public Nullable<int> id_component { get; set; }
        public Nullable<int> id_kind { get; set; }
        public int id_speciality { get; set; }
        public int p54 { get; set; }
        public Nullable<int> sel_leto { get; set; }
        public int leave_rate { get; set; }
        public double p51 { get; set; }
        public double p52 { get; set; }
        public double p53 { get; set; }
        public Nullable<double> seminar { get; set; }
        public int id_control { get; set; }
        public string s_fio { get; set; }
        public string p43 { get; set; }
        public string p30 { get; set; }
        public string p34 { get; set; }
        public string f1 { get; set; }
        public string p22 { get; set; }
        public string p20 { get; set; }
        public string p45 { get; set; }
        public string s_component { get; set; }
    }
}
