//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualModulPermissGROUP
    {
        public int id_IndividualModulPermissGROUP { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_semester { get; set; }
        public Nullable<System.DateTime> beg_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> id_modul { get; set; }
        public Nullable<int> id_f_e { get; set; }
        public Nullable<int> id_ebe_var { get; set; }
        public Nullable<int> id_AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public string host { get; set; }
    }
}
