//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualModulPermissPotok
    {
        public int id_IndividualModulPermissPotok { get; set; }
        public Nullable<int> id_RRNKkrdt { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_year { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> id_modul { get; set; }
        public Nullable<int> id_semester { get; set; }
        public Nullable<System.DateTime> begDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> vid_rrnk { get; set; }
        public Nullable<int> id_rrnk_all { get; set; }
        public Nullable<int> id_ebe_var { get; set; }
        public Nullable<int> subgroup { get; set; }
        public Nullable<int> id_f_e { get; set; }
        public Nullable<int> id_w_s { get; set; }
    }
}
