//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoOnTesting
    {
        public int IDStudent { get; set; }
        public Nullable<int> Building { get; set; }
        public Nullable<int> Audience { get; set; }
        public Nullable<int> NumberPlace { get; set; }
        public Nullable<int> AmountPlace { get; set; }
        public Nullable<System.DateTime> DateExam { get; set; }
        public Nullable<short> Mathematics { get; set; }
        public Nullable<short> Physics { get; set; }
        public Nullable<short> Chemistry { get; set; }
        public Nullable<short> History { get; set; }
        public Nullable<short> Geography { get; set; }
        public Nullable<short> Literature { get; set; }
        public Nullable<short> Economice { get; set; }
        public Nullable<short> Informatics { get; set; }
        public Nullable<short> Biologies { get; set; }
        public Nullable<short> Language { get; set; }
        public Nullable<short> RusLanguage { get; set; }
        public Nullable<short> KyrLanguage { get; set; }
        public Nullable<short> EngLanguage { get; set; }
        public Nullable<short> DocLanguage { get; set; }
        public Nullable<short> FrnLanguage { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> MinEstimation { get; set; }
        public Nullable<bool> OutsideОfСomp { get; set; }
        public Nullable<bool> OneExamin { get; set; }
        public bool SuccessTest { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public string AVN_User_Update { get; set; }
        public string sobesed { get; set; }
        public string vnekonkurs { get; set; }
    }
}
