//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoSchool
    {
        public string NameCity { get; set; }
        public string NameDistrict { get; set; }
        public string NameRegion { get; set; }
        public string NameVillage { get; set; }
        public string CallEducat { get; set; }
        public string NameEdInst { get; set; }
        public int IDCall { get; set; }
        public Nullable<int> IDRegion { get; set; }
        public Nullable<int> IDVillage { get; set; }
        public Nullable<int> IDType { get; set; }
        public Nullable<int> IDDistrict { get; set; }
        public Nullable<int> IDCity { get; set; }
        public string republic { get; set; }
    }
}
