//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KafSecurity
    {
        public int id_kafSecurity { get; set; }
        public Nullable<int> id_kafLogin { get; set; }
        public Nullable<int> id_kafedra { get; set; }
    
        public virtual kafedra kafedra { get; set; }
        public virtual kafLogins kafLogins { get; set; }
    }
}
