//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class kass_2
    {
        public int id_kassa { get; set; }
        public System.DateTime p103 { get; set; }
        public int p104 { get; set; }
        public string p104_1 { get; set; }
        public string name_shet { get; set; }
        public Nullable<double> e_p102 { get; set; }
        public string shet { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public string dopol { get; set; }
        public Nullable<int> id_abiturient { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public Nullable<int> id_slushatel { get; set; }
        public int id_v_opl { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_rate { get; set; }
        public Nullable<int> id_uslug { get; set; }
        public string uslugi { get; set; }
    }
}
