//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class kol_st_subgroup
    {
        public int id_a_year { get; set; }
        public int id_kafedra { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public int id_w_s { get; set; }
        public Nullable<byte> subgroup { get; set; }
        public Nullable<int> id_disciplineName { get; set; }
        public int id_discipline { get; set; }
        public int id_examination { get; set; }
        public Nullable<long> kol_st { get; set; }
    }
}
