//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class kor_mov_2
    {
        public Nullable<int> id_speciality { get; set; }
        public int id_a_year { get; set; }
        public Nullable<int> count_rate { get; set; }
        public int id_student { get; set; }
        public string s_fio { get; set; }
    }
}
