//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language_options
    {
        public int id_lang_options { get; set; }
        public Nullable<int> id_lang { get; set; }
        public Nullable<int> id_level { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public Nullable<int> id_level_read { get; set; }
        public Nullable<int> id_level_speak { get; set; }
        public Nullable<int> id_level_write { get; set; }
    
        public virtual languages languages { get; set; }
        public virtual Level Level { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
