//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library_dolg
    {
        public int id_library_dolg { get; set; }
        public Nullable<int> id_st_tech { get; set; }
        public Nullable<int> Library_dolg1 { get; set; }
        public Nullable<int> s_t { get; set; }
    }
}
