//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup_S_FIO_slushatel
    {
        public Nullable<int> id_student { get; set; }
        public string p1 { get; set; }
        public string p2 { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public string s_fio { get; set; }
        public int id_AVN_user { get; set; }
        public int id_group_slushatel { get; set; }
        public string name_short { get; set; }
    }
}
