//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup_S_FIO_Payment
    {
        public int id_student { get; set; }
        public string s_fio { get; set; }
        public string s { get; set; }
        public string p1 { get; set; }
        public string p2 { get; set; }
        public Nullable<int> id_kassa { get; set; }
        public string first_p1 { get; set; }
        public string SS_FIO { get; set; }
    }
}
