//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark_mag_est
    {
        public string tableName { get; set; }
        public string FieldName { get; set; }
        public string oldValue { get; set; }
        public string newValue { get; set; }
        public int id_group { get; set; }
        public int id_student { get; set; }
        public int id_examination { get; set; }
        public int id_estimation { get; set; }
        public int id_discipline { get; set; }
        public int id_semester { get; set; }
        public int id_f_est { get; set; }
        public int id_user { get; set; }
        public string userComp { get; set; }
        public System.DateTime updated { get; set; }
        public int id_teacher { get; set; }
    }
}
