//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class mil_card_
    {
        public int id_mil_card { get; set; }
        public Nullable<int> id_mil_name { get; set; }
        public Nullable<int> id_valid { get; set; }
        public string voencom { get; set; }
        public Nullable<int> id_R_voisk { get; set; }
        public string Sostav { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public Nullable<bool> Voinsk_uchet { get; set; }
        public string Vus { get; set; }
    
        public virtual Mil_name Mil_name { get; set; }
        public virtual Mil_R_Voisk Mil_R_Voisk { get; set; }
        public virtual Mil_valid Mil_valid { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
