//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileStudentAdmission
    {
        public int MobileStudentAdmissionID { get; set; }
        public int IDWS { get; set; }
        public int SendDay { get; set; }
        public int SendMonth { get; set; }
        public System.DateTime RecordTimeStamp { get; set; }
    }
}
