//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileRaportDetail
    {
        public int MobileAnnounceDetailID { get; set; }
        public int MobileAnnounceID { get; set; }
        public int StudentID { get; set; }
        public int CreateUserID { get; set; }
        public System.DateTime RecordTimeStamp { get; set; }
    
        public virtual MobileRaport MobileRaport { get; set; }
    }
}
