//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class mov_mm_edsh
    {
        public int gr_1 { get; set; }
        public int gr_2 { get; set; }
        public int sem_1 { get; set; }
        public int sem_2 { get; set; }
        public Nullable<int> id_estimation { get; set; }
        public Nullable<int> id_f_e { get; set; }
        public int id_discipline { get; set; }
        public int id_examination { get; set; }
        public int id_student { get; set; }
        public Nullable<int> id_teacher { get; set; }
    }
}
