//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class mov_ved_giv
    {
        public int id_reg_vedomost { get; set; }
        public Nullable<int> id_year { get; set; }
        public Nullable<int> id_ws { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> kredit { get; set; }
        public Nullable<int> subgroup { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public Nullable<int> id_ebe_var { get; set; }
        public Nullable<int> id_f_est { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_semester { get; set; }
        public Nullable<int> id_examination { get; set; }
        public string Shifr { get; set; }
        public Nullable<int> kol { get; set; }
    
        public virtual discipline discipline { get; set; }
        public virtual examination examination { get; set; }
        public virtual group_t group_t { get; set; }
        public virtual semester semester { get; set; }
    }
}
