//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class movement_slushatel
    {
        public int id_movement_slushatel { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_group_slushatel { get; set; }
        public Nullable<int> id_prikaz_come_slushatel { get; set; }
        public Nullable<System.DateTime> come_date { get; set; }
        public Nullable<int> id_prikaz_leave_slushatel { get; set; }
        public Nullable<System.DateTime> leave_date { get; set; }
        public string come_reg { get; set; }
        public string leave_reg { get; set; }
    }
}
