//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class nr_ins_kol_st
    {
        public int id_rrnkKrdt { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public int kol_b { get; set; }
        public int kol_k { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<byte> subgroup { get; set; }
        public Nullable<int> id_examination { get; set; }
        public Nullable<int> id_w_s { get; set; }
    }
}
