//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class obrazovanie_teacher
    {
        public int id_obrazovanie_teacher { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_teacher_struktura { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public string Number { get; set; }
        public Nullable<int> id_teacher_stepen { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<System.DateTime> AVN_date { get; set; }
    }
}
