//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class oks_s_c7
    {
        public int id_student { get; set; }
        public int id_group { get; set; }
        public int id_rate { get; set; }
        public int id_come { get; set; }
        public string come_reg { get; set; }
        public Nullable<System.DateTime> come_date { get; set; }
    }
}
