//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class oplata_smeta
    {
        public int id_payment { get; set; }
        public int pe { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public int id_faculty { get; set; }
        public Nullable<int> id_speciality { get; set; }
        public Nullable<int> id_rate { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_student { get; set; }
        public int id_uslug { get; set; }
        public string uslugi { get; set; }
        public double oplata { get; set; }
        public int order { get; set; }
        public string p104_1 { get; set; }
        public int id_v_opl { get; set; }
        public string p105 { get; set; }
        public double smeta { get; set; }
        public string p14_7 { get; set; }
        public System.DateTime data { get; set; }
        public Nullable<int> priv_var { get; set; }
    }
}
