//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otchis_s_2
    {
        public int id_protocols { get; set; }
        public int Id_student { get; set; }
        public int studen_id { get; set; }
        public Nullable<System.DateTime> leave { get; set; }
    }
}
