//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_s1
    {
        public int id_student { get; set; }
        public string s_fio { get; set; }
        public string p20 { get; set; }
        public string p32 { get; set; }
        public string p22 { get; set; }
        public double p106 { get; set; }
        public Nullable<double> p102 { get; set; }
        public string sh_st { get; set; }
        public int IDCitizenship { get; set; }
        public int id_faculty { get; set; }
        public int id_f_educ { get; set; }
    }
}
