//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment3V
    {
        public Nullable<int> id_student { get; set; }
        public double p102 { get; set; }
        public System.DateTime p103 { get; set; }
        public string p104 { get; set; }
        public string p105 { get; set; }
        public string p32 { get; set; }
        public string p25_2 { get; set; }
        public string uslugi { get; set; }
        public Nullable<int> id_AVN_user { get; set; }
    }
}
