//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentForAbit
    {
        public Nullable<int> id_abiturient { get; set; }
        public string uslugi { get; set; }
        public double p102 { get; set; }
        public System.DateTime p103 { get; set; }
        public int id_faculty { get; set; }
        public string p23_2 { get; set; }
    }
}
