//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment1V
    {
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_rate { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<double> sum_opl { get; set; }
        public string p20 { get; set; }
        public string p22 { get; set; }
        public int id_faculty { get; set; }
        public string p32 { get; set; }
        public Nullable<double> p106 { get; set; }
        public string sh_st { get; set; }
        public string p25_2 { get; set; }
        public Nullable<System.DateTime> come_date { get; set; }
        public Nullable<int> percent_privilege { get; set; }
        public string privilege_coment { get; set; }
        public Nullable<int> id_speciality { get; set; }
        public Nullable<double> ost_sum { get; set; }
        public int id_AVN_user { get; set; }
        public int isPrivelag { get; set; }
    }
}
