//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransfer_Virtual
    {
        public int id_PaymentTransferVirtual { get; set; }
        public int id_payment { get; set; }
        public Nullable<int> id_NewYear { get; set; }
        public Nullable<int> id_newRate { get; set; }
        public Nullable<int> id_newGroup { get; set; }
        public Nullable<double> p102NewSpec { get; set; }
        public Nullable<int> id_newSpecP102 { get; set; }
        public Nullable<System.DateTime> ondate { get; set; }
        public Nullable<int> id_v_opl { get; set; }
    }
}
