//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place_of_residence
    {
        public int id_place_of_residence { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_republic { get; set; }
        public Nullable<int> id_regionKR { get; set; }
        public Nullable<int> id_districtKR { get; set; }
        public Nullable<int> id_cityKR { get; set; }
        public Nullable<int> id_villageKR { get; set; }
        public string Address { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
    }
}
