//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_AbitV
    {
        public int id_plan_abit { get; set; }
        public int id_speciality { get; set; }
        public int kol_k { get; set; }
        public int kol_b { get; set; }
        public string NameQualification { get; set; }
        public string p32 { get; set; }
        public string code_spec { get; set; }
    }
}
