//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanAbitForAbiturient
    {
        public int id_plan_abit { get; set; }
        public int id_speciality { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> IDLicence { get; set; }
        public Nullable<int> id_standard { get; set; }
        public Nullable<int> id_qualification { get; set; }
        public string code_spec { get; set; }
        public string AVN_user { get; set; }
        public Nullable<double> Apprenticeship { get; set; }
        public int kol_k { get; set; }
        public int kol_b { get; set; }
    }
}
