//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class prob4
    {
        public Nullable<int> id_speciality { get; set; }
        public string s_fio { get; set; }
        public string p25_2 { get; set; }
        public int p104 { get; set; }
        public double p102 { get; set; }
        public System.DateTime p103 { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public int id_faculty { get; set; }
        public string p105 { get; set; }
        public int id_payment { get; set; }
        public Nullable<int> id_student { get; set; }
    }
}
