//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_krdt_kol_st
    {
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_w_s { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> id_examination { get; set; }
        public Nullable<int> kredit { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<byte> subgroup { get; set; }
        public Nullable<int> id_vid_zaniatiy { get; set; }
        public Nullable<int> kol_b { get; set; }
        public Nullable<int> kol_k { get; set; }
        public int o_z { get; set; }
    }
}
