//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_nagr_rrnk
    {
        public int id_a_year { get; set; }
        public int id_speciality { get; set; }
        public int id_w_s { get; set; }
        public int id_semester { get; set; }
        public int id_discipline { get; set; }
        public int id_examination { get; set; }
        public Nullable<int> Krdt { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public string s_t_fio { get; set; }
        public string p20 { get; set; }
        public Nullable<int> o_z { get; set; }
    }
}
