//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_ss
    {
        public int id_r_ss { get; set; }
        public Nullable<int> rate_movement { get; set; }
        public Nullable<int> sem_movement { get; set; }
        public Nullable<int> rate_educ_sh { get; set; }
        public Nullable<int> sem_educ_sh { get; set; }
        public Nullable<int> sem_mov_leto { get; set; }
    }
}
