//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_UP_kaf
    {
        public int id_a_year { get; set; }
        public int id_w_s { get; set; }
        public Nullable<int> o_z { get; set; }
        public int id_kafedra { get; set; }
        public int id_discipline { get; set; }
        public int id_examination { get; set; }
        public Nullable<int> Krdt { get; set; }
        public Nullable<double> p51 { get; set; }
        public Nullable<double> p52 { get; set; }
        public Nullable<double> p53 { get; set; }
        public string sn_f1 { get; set; }
        public Nullable<int> kol_st { get; set; }
    }
}
