//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class rasp_teacher
    {
        public int id_shcedule { get; set; }
        public Nullable<int> id_year { get; set; }
        public string p32 { get; set; }
        public Nullable<int> u_god { get; set; }
        public int id_w_s { get; set; }
        public string p42 { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public string p34 { get; set; }
        public Nullable<int> kredit { get; set; }
        public string name_korpus { get; set; }
        public int id_auditorium { get; set; }
        public string number { get; set; }
        public Nullable<int> num_nedeli { get; set; }
        public int id_day { get; set; }
        public string briefName { get; set; }
        public int id_time { get; set; }
        public string Time_ { get; set; }
        public int id_teacher { get; set; }
        public string t_fio { get; set; }
        public Nullable<int> id_rrnk { get; set; }
        public Nullable<int> id_rrnkKrdt { get; set; }
        public Nullable<byte> subgroup { get; set; }
        public Nullable<byte> rrnkType { get; set; }
        public string name_vid_zaniatiy { get; set; }
        public Nullable<int> id_group { get; set; }
        public string p20 { get; set; }
        public Nullable<int> id_vid_zaniatiy { get; set; }
    }
}
