//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingView
    {
        public string p32 { get; set; }
        public string p22 { get; set; }
        public string p43 { get; set; }
        public string p20 { get; set; }
        public string t_fio { get; set; }
        public string p30 { get; set; }
        public string p34 { get; set; }
        public double p51 { get; set; }
        public double p52 { get; set; }
        public double p53 { get; set; }
        public string p45 { get; set; }
        public int p54 { get; set; }
        public string f1 { get; set; }
        public int id_speciality { get; set; }
        public int id_group { get; set; }
        public int id_semester { get; set; }
        public string p25_2 { get; set; }
        public string p23_2 { get; set; }
        public Nullable<double> srs { get; set; }
        public Nullable<double> rzr { get; set; }
        public Nullable<double> ind_z { get; set; }
        public Nullable<double> seminar { get; set; }
        public int id_discipline { get; set; }
        public int id_a_year { get; set; }
        public int id_examination { get; set; }
        public int id_faculty { get; set; }
        public int id_rate { get; set; }
        public int id_educ_sh { get; set; }
    }
}
