//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RNK
    {
        public string p32 { get; set; }
        public string p42 { get; set; }
        public string p43 { get; set; }
        public string p25_2 { get; set; }
        public string f1 { get; set; }
        public string p34 { get; set; }
        public string t_fio { get; set; }
    }
}
