//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class rr2_a
    {
        public int id_a_year { get; set; }
        public int id_kafedra { get; set; }
        public string s_t_fio { get; set; }
        public string n_element { get; set; }
        public Nullable<double> times { get; set; }
        public Nullable<int> id_rrnk_elements { get; set; }
        public string n_type_chasov { get; set; }
        public string post { get; set; }
        public Nullable<int> chasy { get; set; }
        public string f1 { get; set; }
        public string p32 { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> kol_b { get; set; }
        public Nullable<int> kol_k { get; set; }
        public Nullable<int> id_kassa { get; set; }
        public int id_w_s { get; set; }
    }
}
