//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class rr_a_rrnk
    {
        public int id_a_year { get; set; }
        public int id_kafedra { get; set; }
        public string p20 { get; set; }
        public string n_element { get; set; }
        public Nullable<double> times { get; set; }
        public int id_discipline { get; set; }
        public int id_semester { get; set; }
        public int id_examination { get; set; }
        public int id_rrnk_elements { get; set; }
        public string n_type_chasov { get; set; }
        public int id_w_s { get; set; }
        public Nullable<int> o_z { get; set; }
        public Nullable<int> sort0 { get; set; }
        public Nullable<int> sort1 { get; set; }
        public int id_umn { get; set; }
        public Nullable<int> dop_el1 { get; set; }
        public int id_faculty { get; set; }
        public int id_speciality { get; set; }
        public Nullable<int> sort3 { get; set; }
        public Nullable<int> id_f_educ_vid { get; set; }
        public Nullable<int> Krdt { get; set; }
        public int id_group { get; set; }
    }
}
