//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRNK_Schedule
    {
        public int id_RRNK_Schedule { get; set; }
        public Nullable<int> vid_rrnk { get; set; }
        public Nullable<int> id_rrnk_krdt { get; set; }
        public Nullable<int> id_auditorium { get; set; }
        public Nullable<int> id_day { get; set; }
        public Nullable<int> id_time { get; set; }
        public Nullable<int> id_korpus { get; set; }
        public Nullable<System.DateTime> beginDay { get; set; }
        public Nullable<System.DateTime> endDay { get; set; }
        public Nullable<int> id_rrnk_all { get; set; }
    }
}
