//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRNK_doljnost
    {
        public int id_rrnk_doljnost { get; set; }
        public string n_doljnost { get; set; }
        public Nullable<int> chasy { get; set; }
        public Nullable<int> id_a_year { get; set; }
    }
}
