//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrnk_elements
    {
        public int id_rrnk_elements { get; set; }
        public string r_element { get; set; }
        public string n_element { get; set; }
        public Nullable<bool> visible { get; set; }
        public Nullable<int> order_pole { get; set; }
        public string formula { get; set; }
        public string short_n_element { get; set; }
    }
}
