//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrnk_f_1_1
    {
        public int id_faculty { get; set; }
        public string p23_1 { get; set; }
        public int id_a_year { get; set; }
        public string p32 { get; set; }
        public int id_kafedra { get; set; }
        public string f1 { get; set; }
        public int id_group { get; set; }
        public string educ_form { get; set; }
        public int id_educ_form { get; set; }
        public string p34 { get; set; }
        public string p20 { get; set; }
        public Nullable<double> p51 { get; set; }
        public Nullable<double> p52 { get; set; }
        public Nullable<double> p53 { get; set; }
        public Nullable<double> rzr { get; set; }
        public Nullable<double> kpr_ind_z_pl { get; set; }
        public Nullable<double> n_kpr_ind_z_pl { get; set; }
        public Nullable<double> seminar { get; set; }
        public int id_semester { get; set; }
        public Nullable<int> kol_st_gr_all { get; set; }
        public Nullable<int> kol_st_gr_all_b { get; set; }
        public Nullable<double> kpr_prov_reyt_rrnk { get; set; }
        public Nullable<double> n_kpr_prov_reyt_rrnk { get; set; }
        public Nullable<double> kpr_ind_z_rrnk { get; set; }
        public Nullable<double> n_kpr_ind_z_rrnk { get; set; }
        public Nullable<int> n_kpr_id_exam { get; set; }
        public Nullable<int> kpr_id_exam { get; set; }
        public Nullable<int> n_kpr_id_teacher_sum { get; set; }
        public Nullable<int> kpr_id_teacher_sum { get; set; }
        public Nullable<int> kpr { get; set; }
        public Nullable<int> n_kpr { get; set; }
        public Nullable<int> kp { get; set; }
        public Nullable<int> kr { get; set; }
        public Nullable<double> n_lk { get; set; }
        public Nullable<double> n_lb { get; set; }
        public Nullable<double> n_pr { get; set; }
        public Nullable<double> n_sem { get; set; }
        public Nullable<double> prov_reyt { get; set; }
        public Nullable<double> rukov_uch_pr { get; set; }
        public Nullable<double> rukov_pr_pr { get; set; }
        public Nullable<double> rukov_pd_pr { get; set; }
        public Nullable<double> rukov_d_proj { get; set; }
        public Nullable<double> gr_kons { get; set; }
        public Nullable<double> ind_kons { get; set; }
        public Nullable<double> recenth_reyt { get; set; }
        public Nullable<double> recenth_kr { get; set; }
        public Nullable<double> recenth_dp { get; set; }
        public Nullable<double> irs { get; set; }
        public Nullable<double> konsul_dl { get; set; }
        public Nullable<double> uchastie_v_gak { get; set; }
        public Nullable<double> prochie { get; set; }
        public Nullable<double> rec_ruk_kontrrab { get; set; }
        public Nullable<double> ind_zan { get; set; }
        public Nullable<double> recenth { get; set; }
        public Nullable<double> rucov { get; set; }
    }
}
