//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrnk_group_plan_stud1
    {
        public int id_educ_sh { get; set; }
        public int id_kafedra { get; set; }
        public int id_a_year { get; set; }
        public int id_w_s { get; set; }
        public int id_semester { get; set; }
        public int id_faculty { get; set; }
        public int id_discipline { get; set; }
        public int id_examination { get; set; }
        public int id_group { get; set; }
        public double p51 { get; set; }
        public double p52 { get; set; }
        public double p53 { get; set; }
        public Nullable<double> rzr { get; set; }
        public Nullable<double> seminar { get; set; }
        public Nullable<double> srs { get; set; }
        public Nullable<double> ind_z { get; set; }
        public int p54 { get; set; }
        public Nullable<int> kol_st_gr_all { get; set; }
        public Nullable<int> kol_st_gr_all_b { get; set; }
        public Nullable<int> o_z { get; set; }
        public int isKPV { get; set; }
        public int id_speciality { get; set; }
    }
}
