//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRNK_pps
    {
        public int id_rrnk_pps { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_rrnk_doljnost { get; set; }
        public Nullable<double> skor_stavka { get; set; }
        public Nullable<int> id_kassa { get; set; }
    }
}
