//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrnk_a2
    {
        public Nullable<int> id_rrnk { get; set; }
        public int id_kafedra { get; set; }
        public string kafedra { get; set; }
        public Nullable<int> id_year { get; set; }
        public string year { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public string teacher { get; set; }
        public Nullable<int> id_semester { get; set; }
        public string semester { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public string discipline { get; set; }
        public Nullable<int> id_examination { get; set; }
        public string examination { get; set; }
        public Nullable<int> id_group { get; set; }
        public string group { get; set; }
        public int id_faculty { get; set; }
        public string faculty { get; set; }
    }
}
