//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrnkPermiss
    {
        public int id_rrnkPermiss { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public Nullable<System.DateTime> begDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    }
}
