//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrnk_aaa
    {
        public Nullable<int> id_rrnk { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_type_chasov { get; set; }
        public Nullable<double> plan_nagr { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_semester { get; set; }
        public int id_kafedra { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> id_examination { get; set; }
        public double p51 { get; set; }
        public double p52 { get; set; }
        public double p53 { get; set; }
        public Nullable<double> seminar { get; set; }
    }
}
