//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrnk_DiscForStud_KPV
    {
        public int id_kafedra { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_semester { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> id_examination { get; set; }
        public Nullable<int> kol_st_gr_all { get; set; }
        public Nullable<int> kol_st_gr_all_b { get; set; }
        public Nullable<int> o_z { get; set; }
        public int isKPV { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<byte> subgroup { get; set; }
        public int id_w_s { get; set; }
        public int id_f_educ { get; set; }
    }
}
