//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRNKDop
    {
        public int id_rrnk_dop { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<double> hour { get; set; }
        public string forWhat { get; set; }
        public Nullable<int> id_type_chasov { get; set; }
        public Nullable<byte> plan_fakt { get; set; }
        public Nullable<int> id_kassa { get; set; }
        public Nullable<int> id_bk { get; set; }
        public int id_ws { get; set; }
    }
}
