//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrnk_a
    {
        public Nullable<int> id_rrnk { get; set; }
        public int id_kafedra { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_semester { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> id_examination { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_type_chasov { get; set; }
        public Nullable<double> plan_nagr { get; set; }
        public Nullable<int> o_z { get; set; }
        public double up_lk { get; set; }
        public double up_lb { get; set; }
        public double up_pr { get; set; }
        public Nullable<double> up_seminar { get; set; }
    }
}
