//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_citizenship
    {
        public Nullable<int> first_Citizenship { get; set; }
        public int Citizenship { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_ws { get; set; }
        public int id_student { get; set; }
        public int id_dv { get; set; }
        public Nullable<int> sel_citizenship { get; set; }
    }
}
