//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_G
    {
        public int id_s_g { get; set; }
        public Nullable<int> id_student { get; set; }
        public string s_fio { get; set; }
        public Nullable<int> id_group { get; set; }
        public string p20 { get; set; }
        public string idid { get; set; }
        public string e_mail { get; set; }
        public Nullable<int> id_bk { get; set; }
        public Nullable<int> id_semester { get; set; }
        public Nullable<int> id_protocols { get; set; }
        public Nullable<int> id_start_semester { get; set; }
        public Nullable<int> id_speciality { get; set; }
    }
}
