//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_g_old
    {
        public string p20 { get; set; }
        public string s_fio { get; set; }
        public int id_student { get; set; }
        public int id_group { get; set; }
        public string sh_st { get; set; }
        public string Expr1 { get; set; }
        public string idid { get; set; }
        public string e_mail { get; set; }
        public int id_bk { get; set; }
    }
}
