//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_g_r
    {
        public int id_a_year { get; set; }
        public string p32 { get; set; }
        public int id_group { get; set; }
        public string p20 { get; set; }
        public int id_rate { get; set; }
        public string p22 { get; set; }
        public int id_student { get; set; }
        public string s_fio { get; set; }
    }
}
