//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHDayOffGroups
    {
        public int ID { get; set; }
        public int AcadYearID { get; set; }
        public bool IsSemestrAutumn { get; set; }
        public int GroupID { get; set; }
        public int WeekDayID { get; set; }
        public short PairNumber { get; set; }
    }
}
