//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEmployeeList
    {
        public int id_teacher { get; set; }
        public string FIO { get; set; }
        public string post { get; set; }
        public int id_leave { get; set; }
        public Nullable<int> id_structure { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public string sn_f1 { get; set; }
        public string t_fio { get; set; }
    }
}
