//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHScheduleList_a
    {
        public int ID { get; set; }
        public int AcadYearID { get; set; }
        public string p32 { get; set; }
        public bool IsSemestrAutumn { get; set; }
        public int id_w_s { get; set; }
        public string p42 { get; set; }
        public int WeekDayID { get; set; }
        public string WeekDayNameShort { get; set; }
        public string WeekDayName { get; set; }
        public short PairNumber { get; set; }
        public int SubGroup { get; set; }
        public int EveryWeek { get; set; }
        public int StudyTypeID { get; set; }
        public string StudyTypeName { get; set; }
        public int SubjectID { get; set; }
        public string s_p34 { get; set; }
        public string p34 { get; set; }
        public string SubjectName { get; set; }
        public string SubjectShortName { get; set; }
        public int EmployeeID { get; set; }
        public string FIO { get; set; }
        public string FullFIO { get; set; }
        public Nullable<int> EmployeeID2 { get; set; }
        public string FIO2 { get; set; }
        public Nullable<int> id_korpus { get; set; }
        public string name_korpus { get; set; }
        public int AuditoryID { get; set; }
        public string AuditoryName { get; set; }
        public Nullable<int> KafedraID { get; set; }
        public string KafedraName { get; set; }
        public string KafedraFullName { get; set; }
        public Nullable<int> beg_nedeli { get; set; }
        public Nullable<int> end_nedeli { get; set; }
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public string Groups { get; set; }
        public int id_faculty { get; set; }
        public string p23_1 { get; set; }
        public string p23_2 { get; set; }
        public int id_f_educ { get; set; }
        public string p108 { get; set; }
    }
}
