//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHScheduleList_old
    {
        public int ID { get; set; }
        public int AcadYearID { get; set; }
        public bool IsSemestrAutumn { get; set; }
        public int WeekDayID { get; set; }
        public short PairNumber { get; set; }
        public int SubGroup { get; set; }
        public int EveryWeek { get; set; }
        public int StudyTypeID { get; set; }
        public int SubjectID { get; set; }
        public int EmployeeID { get; set; }
        public int AuditoryID { get; set; }
        public Nullable<int> KafedraID { get; set; }
        public Nullable<int> beg_nedeli { get; set; }
        public Nullable<int> end_nedeli { get; set; }
        public Nullable<int> EmployeeID2 { get; set; }
        public Nullable<System.DateTime> Sh_Date { get; set; }
        public Nullable<int> id_time { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_Update { get; set; }
        public string host { get; set; }
        public string AuditoryName { get; set; }
        public string SubjectName { get; set; }
        public string StudyTypeName { get; set; }
        public string FullFIO { get; set; }
        public string FIO { get; set; }
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public string Groups { get; set; }
    }
}
