//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHScheduleGroups
    {
        public int ID { get; set; }
        public int ScheduleID { get; set; }
        public int GroupID { get; set; }
        public Nullable<System.DateTime> AVN_Update { get; set; }
        public string host { get; set; }
    
        public virtual SCHSchedule SCHSchedule { get; set; }
    }
}
