//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHSchedule_discp_pasp
    {
        public int id_discip_rast { get; set; }
        public string p34 { get; set; }
        public string s_p34 { get; set; }
        public string code_discipline { get; set; }
        public string rasp_code_discipline { get; set; }
        public string p34_kg { get; set; }
    }
}
