//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScientificActivity
    {
        public int id_ScientificActivity { get; set; }
        public Nullable<int> id_t_fio { get; set; }
        public Nullable<int> id_uch_step { get; set; }
        public Nullable<int> id_uch_zvanie { get; set; }
        public Nullable<int> id_spec_code { get; set; }
        public Nullable<short> yearProtection { get; set; }
        public string theme { get; set; }
        public string val1 { get; set; }
        public string val2 { get; set; }
        public string val3 { get; set; }
    }
}
