//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelIdvil
    {
        public int IDVillage { get; set; }
        public int IDDistrict { get; set; }
        public string NameVillage { get; set; }
        public Nullable<short> IDAttribute { get; set; }
        public string Expr1 { get; set; }
    }
}
