//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class smeta
    {
        public int id_smeta { get; set; }
        public int id_speciality { get; set; }
        public int id_rate { get; set; }
        public int id_country { get; set; }
        public int id_a_year { get; set; }
        public double p106 { get; set; }
        public string oper { get; set; }
        public Nullable<System.DateTime> u_date { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
    
        public virtual a_year a_year { get; set; }
        public virtual com_sfe com_sfe { get; set; }
        public virtual country country { get; set; }
        public virtual rate rate { get; set; }
    }
}
