//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class smeta_a_BudgetContract
    {
        public int id_a_year { get; set; }
        public int id_rate { get; set; }
        public Nullable<int> p_sem { get; set; }
        public int id_group { get; set; }
        public int id_student { get; set; }
        public Nullable<System.DateTime> come_date { get; set; }
        public Nullable<System.DateTime> leave_date { get; set; }
        public Nullable<double> sem_p106 { get; set; }
        public int id_leave { get; set; }
        public int sel_d { get; set; }
        public int id_bk { get; set; }
        public int id_faculty { get; set; }
    }
}
