//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class speciality_form
    {
        public int id_f_educ { get; set; }
        public Nullable<int> id_login { get; set; }
        public Nullable<int> id_speciality { get; set; }
        public string p25_2 { get; set; }
        public int id_faculty { get; set; }
        public Nullable<int> id_obem_chasov { get; set; }
    }
}
