//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialityRR
    {
        public int id_speciality { get; set; }
        public string p25_1 { get; set; }
        public string p25_2 { get; set; }
        public Nullable<int> id_direction { get; set; }
        public Nullable<int> id_opl { get; set; }
        public string p23_1 { get; set; }
        public string p108 { get; set; }
        public int id_f_educ { get; set; }
        public int id_faculty { get; set; }
        public string p25_21 { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> kol_k { get; set; }
        public Nullable<int> kol_b { get; set; }
        public Nullable<bool> visible { get; set; }
        public Nullable<int> max_rate_id { get; set; }
    }
}
