//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRS_v_groups_students_prep
    {
        public int id_group { get; set; }
        public string p20 { get; set; }
        public int id_discipline { get; set; }
        public Nullable<int> id_teacher { get; set; }
    }
}
