//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_23
    {
        public Nullable<int> id_otdel_1 { get; set; }
        public Nullable<int> id_otdel_2 { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public int id_post { get; set; }
        public int id_vakansiya { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public float empty_vacation { get; set; }
    }
}
