//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_info_View
    {
        public int id_discipline { get; set; }
        public int id_semester { get; set; }
        public int id_examination { get; set; }
        public string p30 { get; set; }
        public string p31 { get; set; }
        public Nullable<double> m1 { get; set; }
        public Nullable<double> m2 { get; set; }
        public Nullable<double> m3 { get; set; }
        public Nullable<double> m4 { get; set; }
        public Nullable<double> dop { get; set; }
        public double ball { get; set; }
        public string p34 { get; set; }
        public int id_estimation { get; set; }
        public int id_group { get; set; }
        public int id_teacher { get; set; }
        public string p35 { get; set; }
        public System.DateTime p36 { get; set; }
        public int id_student { get; set; }
        public int id_f_est { get; set; }
        public int Expr1 { get; set; }
        public int id_mark_mag { get; set; }
    }
}
