//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Po_id_Group
    {
        public string p20 { get; set; }
        public int id_group { get; set; }
        public Nullable<int> id_student { get; set; }
        public string idid { get; set; }
        public string s_fio { get; set; }
        public Nullable<int> o_z { get; set; }
    }
}
