//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_ORT_balls
    {
        public int id_student_ORT_balls { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> tour { get; set; }
        public Nullable<int> id_bk { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public Nullable<int> id_direction { get; set; }
        public Nullable<int> id_speciality { get; set; }
        public string NumberSertRT { get; set; }
        public Nullable<int> BallOnRepsTest { get; set; }
        public Nullable<int> ORT_math { get; set; }
        public Nullable<int> ORT_physics { get; set; }
        public Nullable<int> ORT_english { get; set; }
        public Nullable<int> ORT_chemistry { get; set; }
        public Nullable<int> ORT_history { get; set; }
        public Nullable<int> ORT_biology { get; set; }
    }
}
