//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsGroup
    {
        public string idid { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public int id_faculty { get; set; }
        public int id_speciality { get; set; }
        public int id_student { get; set; }
        public int IDLanguage { get; set; }
        public string p23_2 { get; set; }
        public string p25_2 { get; set; }
        public string ab_fio { get; set; }
        public string NameLanguage { get; set; }
        public string v2 { get; set; }
    }
}
