//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class sv_2
    {
        public int id_faculty { get; set; }
        public int id_a_year { get; set; }
        public int id_group { get; set; }
        public int id_student { get; set; }
        public int id_semester { get; set; }
        public int id_bk { get; set; }
        public Nullable<int> k_dis { get; set; }
        public int kol_st { get; set; }
        public Nullable<int> os { get; set; }
        public Nullable<int> os_nb { get; set; }
        public Nullable<int> os_otl { get; set; }
        public Nullable<int> os_hor_otl { get; set; }
        public Nullable<int> os_ud { get; set; }
        public Nullable<int> os_neud { get; set; }
        public Nullable<int> neud { get; set; }
        public Nullable<int> pvp { get; set; }
        public Nullable<int> zachet { get; set; }
    }
}
