//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class sv_a_u
    {
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_semester { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> id_examination { get; set; }
        public Nullable<int> id_estimation { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public Nullable<double> ball { get; set; }
        public Nullable<System.DateTime> p36 { get; set; }
        public Nullable<int> id_f_est { get; set; }
        public Nullable<int> id_component { get; set; }
        public Nullable<int> id_kind { get; set; }
        public Nullable<int> id_speciality { get; set; }
        public int p54 { get; set; }
        public Nullable<int> descGroupNum { get; set; }
        public Nullable<int> sel_leto { get; set; }
        public int leave_rate { get; set; }
        public double p51 { get; set; }
        public double p52 { get; set; }
        public double p53 { get; set; }
        public Nullable<double> seminar { get; set; }
        public int id_control { get; set; }
        public Nullable<double> m1 { get; set; }
        public Nullable<double> m2 { get; set; }
        public Nullable<double> m3 { get; set; }
        public Nullable<double> m4 { get; set; }
        public Nullable<int> isSelect { get; set; }
        public int sort1 { get; set; }
        public Nullable<int> dg_num { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public int id_educ_sh { get; set; }
        public int id_bk { get; set; }
        public Nullable<int> Krdt { get; set; }
        public Nullable<int> kredits { get; set; }
        public Nullable<int> id_ebe_var { get; set; }
        public Nullable<double> ekv_num { get; set; }
        public string ekv_bukv { get; set; }
    }
}
