//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SV_proced1_temp_t1
    {
        public int id_temp { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_student { get; set; }
        public int id_rate { get; set; }
        public int id_semester { get; set; }
        public string id_discipline { get; set; }
        public int id_w_s { get; set; }
        public int kol_3 { get; set; }
        public Nullable<int> sessiya_sv { get; set; }
        public int id_estimation { get; set; }
        public Nullable<int> id_bk { get; set; }
    }
}
