//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Books
    {
        public int id_books { get; set; }
        public string fileName { get; set; }
        public int id_semester { get; set; }
        public int id_discipline { get; set; }
        public int id_examination { get; set; }
        public int id_speciality { get; set; }
        public int id_user { get; set; }
        public int id_human { get; set; }
        public int id_humanType { get; set; }
        public int id_typeUmk { get; set; }
        public bool isHTMLBook { get; set; }
        public bool isDeleted { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public string description { get; set; }
        public Nullable<short> totalPages { get; set; }
        public Nullable<int> id_bookCategory { get; set; }
        public Nullable<bool> isForEBooks { get; set; }
        public int id_booksShare { get; set; }
        public bool isSharedBookFromEBooks { get; set; }
        public System.DateTime created { get; set; }
        public int kredits { get; set; }
        public short id_forStudentKind { get; set; }
        public bool isTempDel { get; set; }
        public System.DateTime updatedFileDate { get; set; }
    }
}
