//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DynUrl
    {
        public int id_dynUrl { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public bool useParams { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public bool isBaner { get; set; }
        public bool isDeleted { get; set; }
    }
}
