//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EBooks
    {
        public long id_eBook { get; set; }
        public int id_human { get; set; }
        public int id_humanType { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public string description { get; set; }
        public int totalPages { get; set; }
        public string fileName { get; set; }
        public int id_bookCategory { get; set; }
        public System.DateTime created { get; set; }
        public bool isDeleted { get; set; }
    }
}
