//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FileType
    {
        public int id_fileType { get; set; }
        public string filetypeName { get; set; }
        public Nullable<byte> typeMsg { get; set; }
        public Nullable<bool> isForStudent { get; set; }
    }
}
