//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MarkMagModulCopyAccess
    {
        public int id_markMagModulCopyAccess { get; set; }
        public int id_f_est { get; set; }
        public int id_modul { get; set; }
        public int id_ebe_var { get; set; }
        public bool doCopy { get; set; }
    }
}
