//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MessagesForFaculty
    {
        public long id_messageForFaculty { get; set; }
        public int id_faculty { get; set; }
        public int id_human { get; set; }
        public int id_humanType { get; set; }
        public string message { get; set; }
        public string fileName { get; set; }
        public int id_fileType { get; set; }
        public System.DateTime date { get; set; }
        public bool isRead { get; set; }
        public bool isDeleted { get; set; }
    }
}
