//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MessageDetails
    {
        public int id_messageDetails { get; set; }
        public int id_message { get; set; }
        public int id_humanTo { get; set; }
        public int id_humanTypeTo { get; set; }
        public bool read { get; set; }
        public int id_group { get; set; }
    }
}
