//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_nag_sh_lb_update
    {
        public int id_shcedule { get; set; }
        public Nullable<int> old_id_rrnk { get; set; }
        public Nullable<int> new_id_rrnk { get; set; }
    }
}
