//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_nag_sh_lk_RRNK_new_LK_potok
    {
        public Nullable<int> id_year { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public int subgroup { get; set; }
        public int prov_reyt { get; set; }
        public string AVN_user { get; set; }
        public System.DateTime AVN_update { get; set; }
        public Nullable<int> id_examination { get; set; }
        public Nullable<int> id_w_s { get; set; }
        public int plan_fakt { get; set; }
        public int id_o_z { get; set; }
        public int id_ebe_var { get; set; }
        public Nullable<int> id_vid_zaniatiy { get; set; }
        public int id_f_educ { get; set; }
        public Nullable<int> kredit { get; set; }
    }
}
