//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OnlinePaymentCheckCommandLog
    {
        public long id_onlinePaymentCheckCommandLog { get; set; }
        public string account { get; set; }
        public string requestHash { get; set; }
        public System.DateTime lastDateCall { get; set; }
        public int numberOfCalls { get; set; }
        public string request { get; set; }
        public string fromAddress { get; set; }
        public byte type { get; set; }
    }
}
