//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_rrnk_a
    {
        public int id_rrnk { get; set; }
        public Nullable<int> id_educ_sh { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<double> n_lk { get; set; }
        public Nullable<double> n_lb { get; set; }
        public Nullable<double> n_pr { get; set; }
        public Nullable<double> n_sem { get; set; }
        public Nullable<double> manual_kp { get; set; }
        public Nullable<double> gr_kons { get; set; }
        public Nullable<double> ind_zan { get; set; }
        public Nullable<double> ind_kons { get; set; }
        public Nullable<double> prov_reyt { get; set; }
        public Nullable<double> recenth_reyt { get; set; }
        public Nullable<double> recenth_kr { get; set; }
        public Nullable<double> rukov_uch_pr { get; set; }
        public Nullable<double> rukov_pr_pr { get; set; }
        public Nullable<double> rukov_pd_pr { get; set; }
        public Nullable<double> rukov_d_proj { get; set; }
        public Nullable<double> konsul_dl { get; set; }
        public Nullable<double> recenth_dp { get; set; }
        public Nullable<double> uchastie_v_gak { get; set; }
        public Nullable<double> irs { get; set; }
        public Nullable<double> prochie { get; set; }
        public Nullable<double> rec_ruk_kontrrab { get; set; }
        public Nullable<double> recenth { get; set; }
        public Nullable<double> rucov { get; set; }
        public Nullable<double> indivKonsult { get; set; }
        public Nullable<double> groupKonsult { get; set; }
        public Nullable<double> srsPriemKontrol { get; set; }
        public Nullable<byte> plan_fakt { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public Nullable<double> plann { get; set; }
        public Nullable<double> fakt { get; set; }
        public int vedomost { get; set; }
        public int count_pf { get; set; }
        public int id_type_chasov_p_k { get; set; }
        public int id_type_chasov_p_ch { get; set; }
        public int id_type_chasov_f_k { get; set; }
        public int id_type_chasov_f_ch { get; set; }
        public Nullable<double> online { get; set; }
        public Nullable<double> offline { get; set; }
        public Nullable<double> interactive { get; set; }
        public Nullable<int> id_ebe_var { get; set; }
    }
}
