//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_saved_balanceSummer
    {
        public int id { get; set; }
        public int id_year { get; set; }
        public int id_faculty { get; set; }
        public int id_rate { get; set; }
        public int sum { get; set; }
        public System.DateTime AVN_date { get; set; }
    }
}
