//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_saved_balance
    {
        public int id_saved_balance { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public Nullable<int> id_rate { get; set; }
        public Nullable<int> id_ws { get; set; }
        public Nullable<double> sum_balance { get; set; }
        public Nullable<System.DateTime> saved_date { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public Nullable<int> var { get; set; }
        public Nullable<int> id_bk { get; set; }
    }
}
