//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ScheduleForDepartment
    {
        public int id_scheduleForDepartment { get; set; }
        public int id_a_year { get; set; }
        public int id_w_s { get; set; }
        public int id_discipline { get; set; }
        public int kredit { get; set; }
        public int id_nedeli { get; set; }
        public int id_day { get; set; }
        public int id_time { get; set; }
        public int id_kafedra { get; set; }
        public int id_vid_zaniatiy { get; set; }
        public int id_group { get; set; }
        public int id_auditorium { get; set; }
    }
}
