//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SmsDateAutoSend
    {
        public int id_smsDateAutoSend { get; set; }
        public byte id_smsAutoSendKind { get; set; }
        public byte month { get; set; }
        public byte day { get; set; }
    }
}
