//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SmsActionLog
    {
        public long id_smsActionLog { get; set; }
        public long id_smsMessage { get; set; }
        public int id_user { get; set; }
        public int id_userType { get; set; }
        public string phoneNumber { get; set; }
    }
}
