//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StudentDiscount
    {
        public int id_StudentDiscount { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_rate { get; set; }
        public int id_student { get; set; }
        public int id_year { get; set; }
        public double sumDiscount { get; set; }
    }
}
