//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StudentJournalVisit
    {
        public long id_studentJournalVisit { get; set; }
        public int id_teacher { get; set; }
        public int id_a_year { get; set; }
        public int id_w_s { get; set; }
        public int id_student { get; set; }
        public int id_studentGroup { get; set; }
        public int id_semesterOrWs { get; set; }
        public int id_groupOrPorok { get; set; }
        public bool isPotok { get; set; }
        public int id_discipline { get; set; }
        public int credits { get; set; }
        public System.DateTime visitDate { get; set; }
        public bool isVisited { get; set; }
        public int id_vid_zaniatiy { get; set; }
        public byte timesCount { get; set; }
        public int id_time { get; set; }
    }
}
