//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StudyAgreements
    {
        public int id_studyAgreement { get; set; }
        public int id_university { get; set; }
        public int id_user { get; set; }
        public int id_country { get; set; }
        public int id_institution { get; set; }
        public System.DateTime signingDate { get; set; }
        public System.DateTime validity { get; set; }
        public string collaborationArea { get; set; }
        public string note { get; set; }
        public string acceptedFiles { get; set; }
        public string filesForPdf { get; set; }
        public bool isDeleted { get; set; }
    }
}
