//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StudentUploadFileTasksSchedule
    {
        public int id_studentUploadFileTasksSchedule { get; set; }
        public int id_a_year { get; set; }
        public int id_w_s { get; set; }
        public int id_group { get; set; }
        public int id_discipline { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
    }
}
