//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TempEducShUpdated
    {
        public long id { get; set; }
        public int id_educ_sh { get; set; }
        public Nullable<int> id_speciality { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_semester { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> id_examination { get; set; }
        public Nullable<int> Krdt { get; set; }
        public Nullable<bool> isSelect { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public string Suser { get; set; }
        public Nullable<System.DateTime> updata { get; set; }
    }
}
