//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempttt
    {
        public int id_Questionnaires { get; set; }
        public string Description { get; set; }
        public string QuestionnaireType { get; set; }
        public int id_Questions { get; set; }
        public string QuestionRu { get; set; }
        public int id_Ansvers { get; set; }
        public string AnswerRu { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<int> id_w_s { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public Nullable<int> kol { get; set; }
        public Nullable<int> kol_vop { get; set; }
        public Nullable<decimal> proz { get; set; }
    }
}
