//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_markmagSH
    {
        public int id_temp { get; set; }
        public int id_mark_mag { get; set; }
        public int id_group { get; set; }
        public int id_student { get; set; }
        public int id_examination { get; set; }
        public Nullable<double> ball { get; set; }
        public int id_estimation { get; set; }
        public int id_discipline { get; set; }
        public int id_semester { get; set; }
        public int id_teacher { get; set; }
        public int id_f_est { get; set; }
        public bool isStaticDiscipline { get; set; }
        public int kredits { get; set; }
        public Nullable<int> id_ebe_var { get; set; }
        public System.DateTime p36 { get; set; }
    }
}
