//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_c_1
    {
        public int id_teacher { get; set; }
        public string oper { get; set; }
        public Nullable<System.DateTime> u_date { get; set; }
        public string p35 { get; set; }
        public System.DateTime p36 { get; set; }
        public string p109 { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public string p20 { get; set; }
        public string p31 { get; set; }
        public int id_estimation { get; set; }
        public int kredits { get; set; }
        public int id_group { get; set; }
        public int id_examination { get; set; }
        public int id_semester { get; set; }
        public int id_discipline { get; set; }
    }
}
