//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_Ainura
    {
        public int id_a_year { get; set; }
        public string p32 { get; set; }
        public int id_faculty { get; set; }
        public string p23_1 { get; set; }
        public int id_group { get; set; }
        public string p20 { get; set; }
        public int id_rate { get; set; }
        public string p22 { get; set; }
        public int id_student { get; set; }
        public string S_f { get; set; }
        public string S_n { get; set; }
        public string S_o { get; set; }
        public string S_login { get; set; }
        public string S_password { get; set; }
        public string p42 { get; set; }
        public int id_discipline { get; set; }
        public string p34 { get; set; }
        public int id_kafedra { get; set; }
        public string kafedra { get; set; }
        public string spec { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public string p26 { get; set; }
        public string p27 { get; set; }
        public string p28 { get; set; }
    }
}
