//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_del_date
    {
        public long id_logDeleted { get; set; }
        public int id_field { get; set; }
        public string id_student { get; set; }
        public System.DateTime deleted { get; set; }
        public int id_user { get; set; }
        public string userComp { get; set; }
    }
}
