//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_test
    {
        public Nullable<int> id_a_year { get; set; }
        public int id_w_s { get; set; }
        public string p42 { get; set; }
        public int id_faculty { get; set; }
        public string p23_1 { get; set; }
        public int id_rate { get; set; }
        public string p22 { get; set; }
        public int id_semester { get; set; }
        public string p43 { get; set; }
        public int id_discipline { get; set; }
        public string p34 { get; set; }
        public int id_group { get; set; }
        public string p20 { get; set; }
        public int id_student { get; set; }
        public double ball { get; set; }
        public int id_estimation { get; set; }
        public string p31 { get; set; }
    }
}
