//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_SV_proced1
    {
        public string p32 { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public string p23_2 { get; set; }
        public Nullable<int> id_group { get; set; }
        public string p20 { get; set; }
        public Nullable<int> id_student { get; set; }
        public string s_s_fio_2 { get; set; }
        public string p22 { get; set; }
        public int id_rate { get; set; }
        public int id_semester { get; set; }
        public string p43 { get; set; }
        public int id_w_s { get; set; }
        public string p42 { get; set; }
        public int kol_3 { get; set; }
        public Nullable<int> kol_disc { get; set; }
        public Nullable<int> uch_osn_ses { get; set; }
        public int ne_uch_osn_ses { get; set; }
        public int zdal_na_osn_ses { get; set; }
        public int zdal_na_otl_osn_ses { get; set; }
        public int zdal_na_hor_osn_ses { get; set; }
        public int zdal_na_udov_osn_ses { get; set; }
        public int dolg_1_osn_ses { get; set; }
        public int dolg_2_osn_ses { get; set; }
        public int dolg_3ibolee_osn_ses { get; set; }
        public Nullable<int> uch_dop_ses { get; set; }
        public int zdal_po_vsem_disc_all_ses { get; set; }
        public int dolg_all_ses { get; set; }
        public int dolg_1_all_ses { get; set; }
        public int dolg_2_all_ses { get; set; }
        public int dolg_3ibolee_all_ses { get; set; }
        public Nullable<int> uch_all_ses { get; set; }
        public string p108 { get; set; }
        public string p25_2 { get; set; }
        public Nullable<int> id_speciality { get; set; }
        public int id_f_educ { get; set; }
        public Nullable<int> id_bk { get; set; }
        public int B { get; set; }
        public int K { get; set; }
        public Nullable<int> tolko_dop_ses { get; set; }
    }
}
