//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_a
    {
        public Nullable<int> id_mark_mag_del { get; set; }
        public int id_student { get; set; }
        public int id_group { get; set; }
        public int id_examination { get; set; }
        public Nullable<double> m1 { get; set; }
        public Nullable<double> m2 { get; set; }
        public Nullable<double> m3 { get; set; }
        public Nullable<double> m4 { get; set; }
        public Nullable<double> dop { get; set; }
        public Nullable<double> dop2 { get; set; }
        public Nullable<double> ball { get; set; }
        public int id_estimation { get; set; }
        public int id_discipline { get; set; }
        public int id_semester { get; set; }
        public int id_teacher { get; set; }
        public string p35 { get; set; }
        public System.DateTime p36 { get; set; }
        public int id_f_est { get; set; }
        public string oper { get; set; }
        public Nullable<System.DateTime> u_date { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public Nullable<double> m5 { get; set; }
        public Nullable<double> m6 { get; set; }
        public Nullable<double> m7 { get; set; }
        public Nullable<double> m8 { get; set; }
        public Nullable<double> m9 { get; set; }
        public Nullable<double> m10 { get; set; }
        public Nullable<double> m11 { get; set; }
        public Nullable<double> m12 { get; set; }
        public Nullable<int> id_estimation_other { get; set; }
        public Nullable<bool> isStaticDiscipline { get; set; }
        public Nullable<int> kredits { get; set; }
        public Nullable<int> id_ebe_var { get; set; }
    }
}
