//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_13
    {
        public int Id { get; set; }
        public int QuestionnaireId { get; set; }
        public string QuestionRu { get; set; }
        public string AnswerRu { get; set; }
        public int TeacherId { get; set; }
        public int YearId { get; set; }
        public int id_w_s { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> kol { get; set; }
    }
}
