//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_ALL
    {
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_rate { get; set; }
        public Nullable<int> id_semester { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> id_examination { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> Krdt { get; set; }
        public Nullable<int> id_estimation { get; set; }
        public Nullable<bool> isStaticDiscipline { get; set; }
        public int up { get; set; }
        public Nullable<int> dfs { get; set; }
        public int sel { get; set; }
        public string p34 { get; set; }
    }
}
