//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_arch_clean
    {
        public Nullable<int> id_mark_mag { get; set; }
        public int id_group { get; set; }
        public int id_student { get; set; }
        public int id_examination { get; set; }
        public Nullable<double> m1 { get; set; }
        public Nullable<double> m2 { get; set; }
        public Nullable<double> m3 { get; set; }
        public Nullable<double> m4 { get; set; }
        public Nullable<double> dop { get; set; }
        public Nullable<double> dop2 { get; set; }
        public Nullable<double> ball { get; set; }
        public int id_estimation { get; set; }
        public int id_discipline { get; set; }
        public int id_semester { get; set; }
        public int id_teacher { get; set; }
        public Nullable<int> Expr2 { get; set; }
    }
}
