//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_dop_prim_1
    {
        public string p20 { get; set; }
        public string sh_st { get; set; }
        public int id_group { get; set; }
        public int id_student { get; set; }
        public string p22 { get; set; }
        public int id_rate { get; set; }
        public Nullable<int> p106 { get; set; }
        public Nullable<double> sum_opl { get; set; }
        public int msem { get; set; }
        public int id_semester { get; set; }
        public string prim { get; set; }
    }
}
