//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_for_rasp
    {
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_semester { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> potok { get; set; }
        public int Kod_rab { get; set; }
        public double LK { get; set; }
        public double LB { get; set; }
        public double PR { get; set; }
        public Nullable<double> SEM { get; set; }
        public int id_kafedra { get; set; }
        public int aud_specific { get; set; }
    }
}
