//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_online_payment
    {
        public int id { get; set; }
        public Nullable<double> sum { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string descr { get; set; }
        public string account { get; set; }
        public string account2 { get; set; }
        public Nullable<int> id_onlinePaymentPreparedAccount { get; set; }
    }
}
