//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_log2
    {
        public string mm { get; set; }
        public string s_fio { get; set; }
        public string p20 { get; set; }
        public string p43 { get; set; }
        public string p34 { get; set; }
        public Nullable<int> kredits { get; set; }
        public string p30 { get; set; }
        public int id_table { get; set; }
        public string table { get; set; }
        public int id_field { get; set; }
        public string name { get; set; }
        public string detal { get; set; }
        public long id_tableRow { get; set; }
        public string oldValue { get; set; }
        public string newValue { get; set; }
        public int id_user { get; set; }
        public System.DateTime updated { get; set; }
        public string userComp { get; set; }
        public string AVN_login { get; set; }
    }
}
