//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_rasp_error
    {
        public int id_a_year { get; set; }
        public string p32 { get; set; }
        public int id_w_s { get; set; }
        public string p42 { get; set; }
        public int WeekDayID { get; set; }
        public string WeekDayNameShort { get; set; }
        public int EveryWeek { get; set; }
        public Nullable<int> KafedraID { get; set; }
        public int id_teacher { get; set; }
        public string t_fio { get; set; }
        public Nullable<int> kol_disp { get; set; }
    }
}
