//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolTable
    {
        public int IDRecord { get; set; }
        public string InstituteName { get; set; }
        public string InstituteSmallName { get; set; }
        public string InstituteNameOf { get; set; }
        public string RectorName { get; set; }
        public string OperatorName { get; set; }
        public string Minist { get; set; }
    }
}
