//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnk_rs_naz
    {
        public string id_ua { get; set; }
        public int id_country { get; set; }
        public string s_p14_7 { get; set; }
        public Nullable<int> kol_st_b { get; set; }
        public Nullable<int> kol_st_k { get; set; }
        public Nullable<int> kol_st_m { get; set; }
        public Nullable<int> kol_st_j { get; set; }
        public Nullable<int> kol_st1 { get; set; }
    }
}
