//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class uchk_ds
    {
        public int id_group { get; set; }
        public int id_semester { get; set; }
        public Nullable<int> id_component { get; set; }
        public Nullable<int> id_kind { get; set; }
        public int id_discipline { get; set; }
        public int id_examination { get; set; }
        public int p54 { get; set; }
        public int id_kafedra { get; set; }
        public string p45 { get; set; }
        public double p51 { get; set; }
        public double p52 { get; set; }
        public double p53 { get; set; }
        public Nullable<double> seminar { get; set; }
        public string sh_st { get; set; }
        public int id_student { get; set; }
    }
}
