//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_faculty
    {
        public int id { get; set; }
        public string f_user_name { get; set; }
        public string user { get; set; }
        public string user_name { get; set; }
        public Nullable<int> faculty { get; set; }
        public Nullable<int> id_login { get; set; }
        public string OKS { get; set; }
        public string OKPPS { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
    }
}
