//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V1
    {
        public double Expr1 { get; set; }
        public decimal id_onlinePaymentStream { get; set; }
        public int id_v_opl { get; set; }
        public Nullable<int> id_student { get; set; }
        public System.DateTime p103 { get; set; }
    }
}
