//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V__EDUC_SH
    {
        public int id_a_year { get; set; }
        public string god { get; set; }
        public int id_w_s { get; set; }
        public string p42 { get; set; }
        public int id_faculty { get; set; }
        public string fac { get; set; }
        public int id_speciality { get; set; }
        public string sh_spec { get; set; }
        public string spec { get; set; }
        public int id_rate { get; set; }
        public string p22 { get; set; }
        public int id_group { get; set; }
        public string p20 { get; set; }
        public Nullable<int> id_component { get; set; }
        public string s_component { get; set; }
        public Nullable<int> id_kind { get; set; }
        public string s_kind { get; set; }
        public int id_discipline { get; set; }
        public string p34 { get; set; }
        public int id_kafedra { get; set; }
        public string sn_f1 { get; set; }
        public string f1 { get; set; }
        public int id_examination { get; set; }
        public string p30 { get; set; }
        public Nullable<int> Krdt { get; set; }
        public double lk { get; set; }
        public double lb { get; set; }
        public double pr { get; set; }
        public double seminar { get; set; }
        public int srs { get; set; }
        public double vsego { get; set; }
    }
}
