//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_anketirovanie3
    {
        public int id { get; set; }
        public Nullable<int> id_student { get; set; }
        public string s_fio { get; set; }
        public int SemesterId { get; set; }
        public int DisciplineId { get; set; }
        public int TeacherId { get; set; }
        public Nullable<int> Sum { get; set; }
        public int id_anket { get; set; }
    }
}
