//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_anket_vsego_st_movment
    {
        public int id_a_year { get; set; }
        public string p32 { get; set; }
        public int id_w_s { get; set; }
        public int id_faculty { get; set; }
        public string p23_1 { get; set; }
        public Nullable<int> kol_vsego { get; set; }
    }
}
