//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ank_c
    {
        public int QuestionnairesId { get; set; }
        public int id_a_year { get; set; }
        public int id_w_s { get; set; }
        public int id_semester { get; set; }
        public int id_discipline { get; set; }
        public int id_teacher { get; set; }
        public int id_group { get; set; }
        public Nullable<decimal> C1 { get; set; }
        public Nullable<decimal> C2 { get; set; }
        public Nullable<decimal> C3 { get; set; }
        public Nullable<decimal> C4 { get; set; }
        public Nullable<decimal> C5 { get; set; }
        public Nullable<decimal> C6 { get; set; }
        public Nullable<decimal> C7 { get; set; }
        public Nullable<decimal> C8 { get; set; }
        public Nullable<decimal> C9 { get; set; }
        public Nullable<decimal> C10 { get; set; }
        public Nullable<decimal> C11 { get; set; }
        public Nullable<decimal> C12 { get; set; }
        public Nullable<decimal> C13 { get; set; }
        public Nullable<decimal> C14 { get; set; }
        public Nullable<decimal> C15 { get; set; }
        public Nullable<decimal> C16 { get; set; }
        public Nullable<decimal> C17 { get; set; }
        public Nullable<decimal> C18 { get; set; }
        public Nullable<decimal> C19 { get; set; }
        public Nullable<decimal> C20 { get; set; }
    }
}
