//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ank_b
    {
        public int QuestionnairesId { get; set; }
        public int id_a_year { get; set; }
        public int id_w_s { get; set; }
        public int id_semester { get; set; }
        public int id_discipline { get; set; }
        public int id_teacher { get; set; }
        public int id_group { get; set; }
        public int id_Question { get; set; }
        public string QuestionRu { get; set; }
        public Nullable<decimal> sred { get; set; }
    }
}
