//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ank
    {
        public int QuestionnairesId { get; set; }
        public int id_a_year { get; set; }
        public int id_w_s { get; set; }
        public int id_semester { get; set; }
        public int id_discipline { get; set; }
        public int id_teacher { get; set; }
        public int id_group { get; set; }
        public Nullable<int> kol_ank { get; set; }
        public Nullable<decimal> v1 { get; set; }
        public Nullable<decimal> v2 { get; set; }
        public Nullable<decimal> v3 { get; set; }
        public Nullable<decimal> v4 { get; set; }
        public Nullable<decimal> v5 { get; set; }
        public Nullable<decimal> v6 { get; set; }
        public Nullable<decimal> v7 { get; set; }
        public Nullable<decimal> v8 { get; set; }
        public Nullable<decimal> v9 { get; set; }
        public Nullable<decimal> v10 { get; set; }
        public Nullable<decimal> v11 { get; set; }
        public Nullable<decimal> v12 { get; set; }
        public Nullable<decimal> v13 { get; set; }
        public int yes { get; set; }
        public int no { get; set; }
        public Nullable<int> C1 { get; set; }
        public Nullable<int> C2 { get; set; }
        public Nullable<int> C3 { get; set; }
        public Nullable<int> C4 { get; set; }
        public Nullable<int> C5 { get; set; }
        public int kol_dis { get; set; }
    }
}
