//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Auditory
    {
        public int id_auditorium { get; set; }
        public string name_korpus { get; set; }
        public string Auditory { get; set; }
        public int contain { get; set; }
        public string specifics { get; set; }
        public int id_specifics { get; set; }
        public string note { get; set; }
        public Nullable<double> square { get; set; }
    }
}
