//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Date_reg_DFS
    {
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_w_s { get; set; }
        public Nullable<int> id_f_educ { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public int id_group { get; set; }
    }
}
