//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_edush
    {
        public int id_speciality { get; set; }
        public int id_a_year { get; set; }
        public Nullable<int> u_god { get; set; }
        public string p32 { get; set; }
        public int id_w_s { get; set; }
        public string p42 { get; set; }
        public int id_semester { get; set; }
        public string p43 { get; set; }
        public int id_faculty { get; set; }
        public int id_kafedra { get; set; }
        public string f1 { get; set; }
        public int id_discipline { get; set; }
        public string p34 { get; set; }
        public Nullable<int> Krdt { get; set; }
        public int id_examination { get; set; }
        public string p30 { get; set; }
        public Nullable<int> id_group { get; set; }
        public string p20 { get; set; }
        public Nullable<int> kol_st { get; set; }
    }
}
