//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_educ_sh_del_RRNKkrdt
    {
        public int id_rrnkKrdt { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public int id_semester { get; set; }
        public int id_speciality { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> id_examination { get; set; }
        public Nullable<int> kredit { get; set; }
    }
}
