//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FXByFaculty
    {
        public Nullable<int> id_student { get; set; }
        public string s_fio { get; set; }
        public int id_group { get; set; }
        public string p20 { get; set; }
        public int id_faculty { get; set; }
        public string p23_1 { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public Nullable<int> id_ebe_var { get; set; }
        public int id_semester { get; set; }
        public int id_w_s { get; set; }
        public string p42 { get; set; }
        public Nullable<double> Expr1 { get; set; }
        public string p34 { get; set; }
        public int id_discipline { get; set; }
        public string p32 { get; set; }
    }
}
