//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IndividualModulPermissPotok_group_discipline
    {
        public Nullable<int> id_a_year { get; set; }
        public int id_w_s { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public int id_semester { get; set; }
        public int id_group { get; set; }
        public int id_discipline { get; set; }
        public string p34 { get; set; }
        public int id_examination { get; set; }
        public string p30 { get; set; }
        public Nullable<int> id_ebe_var { get; set; }
        public int kredits { get; set; }
    }
}
