//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Jurnal_dis
    {
        public Nullable<int> id_a_year { get; set; }
        public int id_w_s { get; set; }
        public int id_rate { get; set; }
        public Nullable<int> id_semester { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> kredits { get; set; }
        public Nullable<int> subgroup { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_examination { get; set; }
        public int id_kafedra { get; set; }
        public int id_faculty { get; set; }
    }
}
