//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Jurnal_visit
    {
        public int id_a_year { get; set; }
        public int id_w_s { get; set; }
        public int id_Group { get; set; }
        public int id_teacher { get; set; }
        public int id_discipline { get; set; }
        public int credits { get; set; }
        public bool isPotok { get; set; }
        public System.DateTime visitDate { get; set; }
        public bool kol { get; set; }
        public int id_student { get; set; }
    }
}
