//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Login
    {
        public int id_humanType { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> id_human { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_login { get; set; }
        public string snp { get; set; }
        public int id_human_typeFrom { get; set; }
        public Nullable<int> id_speciality { get; set; }
        public string p20 { get; set; }
        public int id_f_educ { get; set; }
        public Nullable<int> o_z { get; set; }
        public Nullable<bool> canUploadUmk { get; set; }
        public string e_mail { get; set; }
    }
}
