//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_mark_mag_arch
    {
        public int id_mark_mag { get; set; }
        public int id_mark_mag_del { get; set; }
        public int id_group { get; set; }
        public int id_student { get; set; }
        public int id_examination { get; set; }
        public int id_discipline { get; set; }
        public int id_semester { get; set; }
        public string p35 { get; set; }
        public int id_f_est { get; set; }
    }
}
