//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MarkMag_user
    {
        public Nullable<int> id_f_est { get; set; }
        public string p109 { get; set; }
        public Nullable<int> avn13 { get; set; }
        public bool isPersonal { get; set; }
        public int id_user_f_est { get; set; }
        public Nullable<int> id_login { get; set; }
        public string AVN_login { get; set; }
        public string AVN_User { get; set; }
    }
}
