//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_mm_max_ekv
    {
        public int id_group { get; set; }
        public int id_student { get; set; }
        public int id_examination { get; set; }
        public Nullable<double> ball { get; set; }
        public Nullable<int> id_estimation { get; set; }
        public int id_discipline { get; set; }
        public int id_semester { get; set; }
        public int Krdt { get; set; }
        public Nullable<int> id_ebe_var { get; set; }
        public Nullable<double> beg_bal { get; set; }
        public Nullable<double> end_bal { get; set; }
        public Nullable<double> ekv_num { get; set; }
        public string ekv_bukv { get; set; }
        public Nullable<double> krdt_ekv { get; set; }
        public int DOLG { get; set; }
    }
}
