//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MYFIND
    {
        public string table { get; set; }
        public string descr { get; set; }
        public string AVN_User { get; set; }
        public Nullable<System.DateTime> AVN_Update { get; set; }
        public string p20 { get; set; }
        public string s_fio { get; set; }
        public string p34 { get; set; }
        public string p30 { get; set; }
        public string p43 { get; set; }
        public int id_mark_mag { get; set; }
        public string Estimateon___On { get; set; }
        public int id_faculty { get; set; }
    }
}
