//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RRNKkrdt_disipline
    {
        public int id_discipline { get; set; }
        public Nullable<int> id { get; set; }
        public string Discipline { get; set; }
        public int id_f_educ { get; set; }
        public int Krdt { get; set; }
        public int id_kafedra { get; set; }
        public int id_semester { get; set; }
    }
}
