//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_smeta_spec
    {
        public int id_a_year { get; set; }
        public int id_faculty { get; set; }
        public int id_f_educ { get; set; }
        public string p108 { get; set; }
        public Nullable<int> id_direction { get; set; }
        public string p24_1 { get; set; }
        public string p24_2 { get; set; }
        public int id_speciality { get; set; }
        public string p25_1 { get; set; }
        public string p25_2 { get; set; }
        public Nullable<int> id_country { get; set; }
        public string p14_7 { get; set; }
        public double KK1 { get; set; }
        public double KK2 { get; set; }
        public double KK3 { get; set; }
        public double KK4 { get; set; }
        public double KK5 { get; set; }
        public double KK6 { get; set; }
    }
}
