//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Test_samoozenka
    {
        public Nullable<int> id_student { get; set; }
        public string p1 { get; set; }
        public string p2 { get; set; }
        public string p3 { get; set; }
        public int id_test_type { get; set; }
        public string test_type { get; set; }
        public string Description { get; set; }
        public int id_test_category { get; set; }
        public string Names { get; set; }
        public string Descriptionn { get; set; }
        public int id_test_vopros { get; set; }
        public string namess { get; set; }
    }
}
