//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_time
    {
        public int id_time { get; set; }
        public string Time_ { get; set; }
        public Nullable<int> sort { get; set; }
        public Nullable<int> prov_time { get; set; }
        public Nullable<int> vid_time { get; set; }
    }
}
