//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UserInfo
    {
        public int id_AVN_user { get; set; }
        public Nullable<int> id_language { get; set; }
        public string locale { get; set; }
        public string snp { get; set; }
        public bool visible { get; set; }
    }
}
