//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class var_sum
    {
        public int id_var_sum { get; set; }
        public Nullable<int> id_ebe_var { get; set; }
        public Nullable<int> var_sum1 { get; set; }
        public Nullable<int> var_prog { get; set; }
        public string prog { get; set; }
    }
}
