//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class VuzDefaults
    {
        public int id_vuz_defaults { get; set; }
        public string n_avn_prog { get; set; }
        public string descr { get; set; }
        public string n_field { get; set; }
        public int id_field { get; set; }
    }
}
