//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class VV_Respondents
    {
        public int QuestionnairesId { get; set; }
        public int SemesterId { get; set; }
        public int YearId { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> kol_st { get; set; }
    }
}
