//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int id_Work { get; set; }
        public string Doljnost { get; set; }
        public string Name_org { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public string FIO_Dir { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<System.DateTime> Date_Enter { get; set; }
        public Nullable<System.DateTime> Date_Quit { get; set; }
        public Nullable<int> id_type_job { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public string descr { get; set; }
        public string Enter_numPrikaz { get; set; }
        public string Quit_numPrikaz { get; set; }
        public bool First_Check { get; set; }
    
        public virtual @base @base { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
