//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Working
    {
        public int id_working { get; set; }
        public int id_teacher { get; set; }
        public int id_stavka { get; set; }
        public int id_vakansiya { get; set; }
        public int id_base_over { get; set; }
        public Nullable<int> razr { get; set; }
        public int id_prikaz_come { get; set; }
        public string Num_prikaz_Enter { get; set; }
        public System.DateTime date_come { get; set; }
        public Nullable<System.DateTime> from_d { get; set; }
        public Nullable<int> temp_leave { get; set; }
        public int id_leave { get; set; }
        public string Num_prikaz_leave { get; set; }
        public Nullable<System.DateTime> Date_leave { get; set; }
        public string Reason_quit { get; set; }
        public Nullable<System.DateTime> off_date { get; set; }
        public string AVN_user { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public Nullable<double> hourFond { get; set; }
    
        public virtual @base @base { get; set; }
        public virtual Prikaz_come Prikaz_come { get; set; }
        public virtual Prikaz_leave Prikaz_leave { get; set; }
        public virtual Stavka Stavka { get; set; }
        public virtual teacher teacher { get; set; }
        public virtual Vakansii Vakansii { get; set; }
    }
}
