//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class www
    {
        public string fileName { get; set; }
        public int id_discipline { get; set; }
        public int id_human { get; set; }
        public int id_typeUmk { get; set; }
        public int id_books { get; set; }
        public System.DateTime created { get; set; }
        public bool isHTMLBook { get; set; }
    }
}
