//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Faculty_Null
    {
        public int id_InfoOnEdIns { get; set; }
        public int IDStudent { get; set; }
        public string ab_fio { get; set; }
        public string NumberSertRT { get; set; }
        public Nullable<int> Faculties { get; set; }
        public Nullable<System.DateTime> AVN_update { get; set; }
        public string name { get; set; }
    }
}
