//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_rasp_DFS
    {
        public Nullable<int> id_a_year { get; set; }
        public string p32 { get; set; }
        public int id_faculty { get; set; }
        public string p23_1 { get; set; }
        public Nullable<int> id_semester { get; set; }
        public string p43 { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public string p34 { get; set; }
        public int kredits { get; set; }
        public Nullable<byte> potok { get; set; }
        public int id_kafedra { get; set; }
        public string f1 { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public string s_t_fio { get; set; }
        public Nullable<int> id_group { get; set; }
        public string p20 { get; set; }
        public Nullable<int> id_examination { get; set; }
        public string p30 { get; set; }
    }
}
