//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_rasp_yacheika_1
    {
        public int id_shcedule { get; set; }
        public int id_a_year { get; set; }
        public int id_w_s { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public int id_rate { get; set; }
        public Nullable<int> kredit { get; set; }
        public Nullable<int> id_auditorium { get; set; }
        public Nullable<int> id_nedeli { get; set; }
        public int id_faculty { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public Nullable<int> id_vid_zaniatiy { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_time { get; set; }
        public Nullable<int> id_day { get; set; }
        public Nullable<int> day_number { get; set; }
    }
}
