//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Sheduler_RRNKkrdt_y_rasp
    {
        public Nullable<int> id_year { get; set; }
        public string p32 { get; set; }
        public Nullable<int> id_ws { get; set; }
        public string p42 { get; set; }
        public Nullable<int> id_semester { get; set; }
        public string p43 { get; set; }
        public Nullable<int> id_faculty { get; set; }
        public string p23_1 { get; set; }
        public string p23_2 { get; set; }
        public Nullable<int> id_speciality { get; set; }
        public string p25_2 { get; set; }
        public Nullable<int> day_number { get; set; }
        public string Day_name { get; set; }
        public Nullable<int> id_time { get; set; }
        public string Time_ { get; set; }
        public Nullable<int> b_num_nedeli { get; set; }
        public Nullable<int> e_num_nedeli { get; set; }
        public Nullable<int> id_auditorium { get; set; }
        public string aud_num { get; set; }
        public Nullable<int> id_rrnk { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public string p34 { get; set; }
        public Nullable<int> kredit { get; set; }
        public Nullable<int> id_kafedra { get; set; }
        public string f1 { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public string s_t_fio { get; set; }
        public Nullable<byte> subgroup { get; set; }
        public Nullable<int> id_vid_zaniatiy { get; set; }
        public string short_name { get; set; }
        public string name_vid_zaniatiy { get; set; }
        public Nullable<int> id_teacherOwner { get; set; }
        public Nullable<int> id_teacherOwner1 { get; set; }
    }
}
