//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_SV_F83_ots
    {
        public int id_a_year { get; set; }
        public int id_faculty { get; set; }
        public Nullable<int> id_semester { get; set; }
        public int id_group { get; set; }
        public int id_student { get; set; }
        public int id_discipline { get; set; }
        public int id_examination { get; set; }
        public int kredits { get; set; }
        public Nullable<int> id_estimation { get; set; }
    }
}
