//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_USPEV_UC_B
    {
        public string p20 { get; set; }
        public string s_fio { get; set; }
        public string p22 { get; set; }
        public string p43 { get; set; }
        public string p34 { get; set; }
        public Nullable<int> p54 { get; set; }
        public string p30 { get; set; }
        public Nullable<double> ball { get; set; }
        public Nullable<System.DateTime> p36 { get; set; }
        public Nullable<int> id_estimation { get; set; }
        public string s_component { get; set; }
        public string s_kind { get; set; }
        public Nullable<int> id_a_year { get; set; }
        public int id_speciality { get; set; }
        public int id_discipline { get; set; }
        public int id_semester { get; set; }
        public string p32 { get; set; }
        public int id_group { get; set; }
        public int id_student { get; set; }
        public Nullable<int> Krdt { get; set; }
        public string p31 { get; set; }
        public Nullable<int> id_ebe_var { get; set; }
        public int id_examination { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public string s_t_fio { get; set; }
        public int registr { get; set; }
    }
}
