//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleKSTUMigration.Avndb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zoomo_VIEW
    {
        public string NumberSertRT { get; set; }
        public string FIO_abit { get; set; }
        public string p24_2 { get; set; }
        public Nullable<int> BallOnRepsTest { get; set; }
        public int matem { get; set; }
        public int phisic { get; set; }
        public int biolog { get; set; }
        public int chem { get; set; }
        public bool Recom_for_reccept { get; set; }
        public bool confirm_date_for_reccept { get; set; }
        public bool Recepted { get; set; }
        public short id_bk { get; set; }
        public string name { get; set; }
        public Nullable<int> Faculties { get; set; }
    }
}
